voluntarily/vly2

package-lock.json, package.json, server/api/opportunity/__tests__/health.spec.js, server/api/opportunity/__tests__/opportunity.spec.js, server/api/person/__tests__/person.spec.js, server/util/mockMongo.js, server/util/test-helpers.js, server/util/test-mongo.js
work around for VP-113  add --serial to the npm test runner so that the tests run in serial. Its a lot slower but avoids failures. Just until I can work out the fix.
=> VP-113 #comment serial flag on tests - slow but works

components/Op/OpListSection.js, components/Op/__tests__/OpListSection.spec.js
removed bad example of usage.  class captured result from api call and placed in local state instead of and as well as redux.   Switched usage so that we use the store values returned from the api call.
Advantage the record now includes a loading flag to control the spinner.
=> Feat/vp 131/op list section state

docs/troubleshooting/ECONRESET in windows.md, lib/auth/__test__/auth.spec.js, package-lock.json, package.json, server/api/interest/__tests__/interest.spec.js, server/api/opportunity/__tests__/opportunity.spec.js, server/api/organisation/__tests__/organisation.spec.js, server/api/person/__tests__/person.spec.js, server/util/test-memory-mongo.js
Cause:  mongoose disconnect. 
we are running tests in parallel.  Although we now use mongo-memory-server to give us multiple parallel databases mongoose is still a single thing.  So mongoose connect connects to different ports but when we call mongoose.disconnect it drops everything.   
Commenting out and the tests run ok.  there may be dangling connections but the tests don't care. 
Tested on Windows.
=> Vp 168 uncaught exceptions when running tests on windows

x/aws/deploy-alpha
Added load balancer to AWS cluster.  Created a new service vly2. 
This change starts the service instead of the previous one.
Also logging to cloud watch is now on.
=> service vly -> vly2 with load balancer

config/config.js, docker-compose-alpha.yml, docker-compose-ecs-atlas.yml, x/ssl/checkssl-alpha
On production servers the api calls are https.  Set the ENV Var APP_URL to default to https://alpha.voluntari.ly.  however in real production the ENV var should be set by the deployment.
=> APP_URL in prod is https

components/Op/OpAdd.js, components/Op/__tests__/OpAdd.spec.js, pages/landing/landing.js
I think this is correct behaviour, unless you want a non op-provider to be able to click the button and then have the opportunity to sigh in with a different account...
=> VP-41: Make New opportunity only available for op-providers

hocs/publicPage.js, lib/__test__/apiCaller.spec.js, lib/apiCaller.js, lib/auth/auth.js, package-lock.json, package.json, pages/op/opdetailpage.js, server/api/image/__tests__/image.spec.js, server/server.js
We want to know if any calls to our backend are authenticated, and if so, by who. We currently use auth0 for authentication and they give us a token we can use. Unfortunately, this token gets "lost" when making server to server calls (during SSR). Before we move forward with an Authentication and Authorization framework, we need to ensure cookies are consistently available. This PR is a baby step towards that end.
=> [VP-213] Forward headers on server to server fetch call

Dockerfile, x/aws/buildimage
Should work, but a bit tricky to test without end to end...
Still needs actual values added to the cirrus build, I will add a wiki page detailing that. They should be added as env vars
BUILD_SMTP_ID and BUILD_SMTP_PWD in the .cirrus.yml file in the env block as ENCRYPTED values
=> Add SMTP_ID and SMTP_PWD to docker env set at build time

server/api/opportunity/__tests__/opportunity.fixture.js, server/api/opportunity/__tests__/opportunity.spec.js, server/api/opportunity/opportunity.controller.js
Backend treats the search query as an array of keywords and will now include any opportunities with  one or more matching keywords, as well as any opps with a matching title, subtitle, or description (as before)
=> Vp 257 include tags in search

components/Op/OpDetailForm.js, components/Op/OpDetailLocation.js, components/Op/__tests__/OpDetailForm.spec.js, components/Op/__tests__/OpDetailLocation.spec.js, lib/redux/reduxApi.js, pages/op/opupdatepage.js, server/api/location/__tests__/location.spec.js, server/api/location/location.controller.js, server/api/location/location.routes.js, server/api/location/locationData.js
Introduces a searchable location input component to both the update page for opportunities, as well as the page for creating new opportunities. Inputs are constrained currently to New Zealand TLAs and regions, as is retrieved from mongoDB via a newly made endpoint. BE/FE tests have been included as well. Example of the component in action is below! (To test, check out updating an opportunity/creating a new opportunity). 
***
=> VP 233 Search by location

components/Search/BigSearch.js, pages/search/DatePickerComponent.js
Fixed the display of date ranges for the BigSearch component. The original JIRA suggested these be formatted as "14 Aug - 16 Aug", but here I've used DD/MM/YY to 
a) remain consistent with the single date selection display, and
b) keep the year displayed
Happy to switch formats if we prefer DD MMM overall.
=> VP-358: Fixed display of date ranges

components/Interest/RegisterInterestSection.js, components/LandingPageComponents/__tests__/FeaturedTwoSection.spec.js, components/Op/OpVolunteerInterestSection.js, components/Op/__tests__/OpCard.spec.js, components/Op/__tests__/OpList.spec.js, pages/op/opdetailpage.js
The reason is that the me props that got passed down to OpVolunteerInterestSection is only an ID string not an object. This caused the server reading an undefined variable then crash the server. 
Minor unit test fix so less warning in the log when unit test is running
=> Bug fix server crash when user click interested

server/api/interest/__tests__/interest.spec.js, server/api/interest/interest.controller.js, server/api/member/__tests__/member.spec.js, server/api/member/member.constants.js, server/api/member/member.controller.js, server/api/member/member.js, server/api/member/member.routes.js
added member entity holding a join between a person and an organisation.  Members can have state of follower, member as well as the intermediate state of requesting to join and exmember.
Patterned on the interest entity. 
Full set of tests, 100% coverage. 
TODO includes adding email notification for membership state changes.
=> VP-421 add member entity and api

lib/redux/reduxApi.js, pages/op/opdetailpage.js, server/api/opportunity/__tests__/opportunity.ability.spec.js, server/api/opportunity/opportunity.ability.js
ReduxApi when perform fetch does not contain any cookie or session with it. So Casl will block all query  for opportunity that has draft status. So the temporary solution would be remove conditions for read action in anonAbilities
=> Temporary remove conditions in opportunity ability

__tests__/home.spec.js, components/Op/OpRecommendations.js, components/Op/__tests__/OpRecommendations.spec.js, lib/redux/reduxApi.js, pages/home/home.js, server/api/opportunity/__tests__/recommendedOps.spec.js, server/api/opportunity/opportunity.controller.js, server/api/opportunity/opportunity.routes.js
This PR fixes the issue where recommended ops aren't showing when they should. 
The problem was due to the initial redux api call filtering the opportunities to only include those I have requested. So I removed this filter and implemented it in the front-end instead, so that the Recommendations component gets passed all ops
=> Fix issue with recommended ops not showing

components/Member/MemberSection.js
Site administrators can create organisations and view the members page to see the the MemberSections containing the lists of members and followers. This is necessary so that they can create the first OrgAdmins who can then add new members and admins etc.
=> VP-420 site admin can see memberSections

components/LandingPageComponents/Hero.js, server/api/location/location.controller.js
VP 369 : Big search in landing page can not search for empty 
*  Proposed Changes
- Remove if condition when search button clicked
<h2> Additionan Info. </h2>
<p>1. Also fix location options in op detail form</p>
<p>2. The Online option will be shown first then the rest will be ordered by alphabetical order</p>
This is the first time I follow the template so it takes me longer than usual
=> Vp 369 big search can t search for nothing

components/Form/Input/RichTextEditor.js, components/Member/MemberSection.js, components/Member/__tests__/MemberSection.spec.js, components/Member/__tests__/MemberSectionInfo.spec.js, components/Org/OrgCard.js, components/Org/OrgDetail.js, components/Org/OrgDetailForm.js, pages/org/orglistpage.js, server/api/organisation/__tests__/organisation.fixture.js, server/api/organisation/organisation.js
When viewing an organisation page the person sees two tabs. An About tab containing general information for the public and a members tab containing information for followers and members.
Depending on the state of membership the person sees different information pages.  These fields are added to the organisation object in the info object.  
OpDetails display and OpDetailsForm updated to collect and show the content.  Most work done by MemberSection
Extensive tests required so that each membership relationship sees the right content. 
The original about field has been moved to an object 'info' that contains fields for about, joiners, followers etc.  This means that existing database records will need to be updated and the old about field deleted. (easiest at this point to recreate the …
=> VP-422 Rich text information pages for members, joiners and followers

pages/org/orgdetailpage.js
When the person is not authenticated then when viewing the Organisation Details page the Follow and Join buttons are not shown.
=> VP-437 Hide follow button for non signed in people

lib/redux/reduxApi.js, pages/org/orgdetailpage.js
When OrgDetails page loads obtain the membership status of the currently signed in person. on Render set the isOrgAdmin flag true if the the current person is in the org membership list as an OrgAdmin.  
Edit Org button is enabled for OrgAdmins and System Admins.
=> VP-274 enable edit button for orgAdmins

components/Person/PersonDetail.js, components/Person/PersonDetailForm.js, components/Person/__tests__/PersonDetailForm.spec.js, lib/redux/reduxApi.js, pages/home/home.js, server/api/person/__tests__/person.fixture.js, server/api/person/__tests__/person.spec.js, server/api/person/person.controller.js, server/api/person/person.js, server/api/person/person.routes.js
When editing their profile, a user (volunteer) can optionally add skills they think they are particularly great in. 
By going to .../home, and clicking on the profile tab and subsequent edit button, a user should now be able to input and save skills they believe they are proficient in.
This information will be used in the future, to recommend relevant opportunities to them, based on these skills.
<h2>Screenshots</h2>
Edits have been made to tests around Person/PersonDetailForm/PersonDetail etc., to factor in new attribute. Most of the testing of the component itself (TagInput/TagDisplay) has already been done in previous PRs.
=> VP-321 add skills to profiles

server/api/health/health.controller.js
created new
* ssl certificate in sydney
* service voluntarily-beta-service
* target group voluntarily-beta-target-group
* application load balancer voluntarily-beta-load-balancer
* security group sg-0741c857d0cd48946, voluntarily-beta-security-group - limiting access to 80 and 443 http.
Add a listener to load balancer for HTTPS with local SSL certificate
Edit listener for HTTP 80 to redirect 301 to Https 
All the above are AWS configuration changes.
add health/log to output message to logfile.
update the name of the voluntarily-beta-service in the x/aws/deploy-beta script
=> VP-310 Enable SSL on Beta 

components/Org/OrgDetail.js, components/Org/OrgDetailForm.js
Fields to hold facebook and twitter links have been added to the organisation record
OrgDetailForm - updated to allow entry of the links.  We don't ask for the full URL but just the user's name. This prevents them pointing the links away from fb or twitter. 
OrgDetail - social links shown in sidebar as icon buttons.
=> VP-386 add facebook and twitter links

server/api/person/__tests__/person.spec.js, server/api/person/person.controller.js, server/api/person/person.routes.js
A bug was introduced last week when the route for people/:id was set to be handled by GetPersonBy in order to add tags to the product.  This was a misunderstanding as this handler only returns one person and if no match is found then returns the first person. 
* Added new listPeople controller along the same pattern as for organisations. This means we can search using mongodb queries and filters. 
* updated controller list
Note this was not picked up as the tests are marked as failing.  This is because listPeople is now covered by an ability and requires the user to be signed in in order to be able to get the list of people.
=> VP-461 People list page is empty, Person Get returns first person

components/Op/OpRecommendations.js, components/Op/__tests__/OpRecommendations.spec.js, package-lock.json, pages/home/home.js, server/api/opportunity/__tests__/recommendedOps.spec.js, server/api/opportunity/opportunity.controller.js, server/api/opportunity/opportunity.util.js, server/api/person/person.controller.js, x/db/op-cars.json, x/db/op-impact.json, x/db/op-litter.json, x/db/op-rocket.json
This PR will introduce new functionality to the component **(OpRecommendations)** into the /home page, to display recommended opportunities from the platform.
These will now either be based on:
* **Location** (e.g opportunities in the exact same region and/or related territories - e.g Kaikoura District and Christchurch City are both territories within the Canterbury region) - _(PREVIOUS FUNCTIONALITY)_
* **Skills** - depending on the number of matching skill tags a given opportunity has with a user, that opportunity gets assigned a value (+1 for each matching tags). These are then ranked based on calculated count, from most to least relevant - _(ADDED FUNCTIONALITY)_
Any questions about this, feel free to ask @darcycox97 or I!!
=> Add recommendations of opportunities based on a user's skills

components/Op/OpDetail.js
rich text field on opportunities was not displaying the full rich text due to an overzealous sanitisation on the client side. This is not required as the server will have already performed the sanitisation.
=> VP-435 remove unnecessary client side sanitization

components/Member/MemberSection.js, components/Member/MemberTable.js
on the members page of organisation the value isMe is used to pass in a flag showing which membership record belongs to the signed in person. This is used on the MemberTable to hide action buttons the membership entry line for the orgAdmin to prevent them removing themselves and locking them out of the admin role.
However updating the redux object seems to cause it to be removed in some circumstances and this results in an exception.  
Instead we now pass in the me id of the person and check the match explicitly.
=> VP-468 remove isMe modifying of membership

pages/op/opdetailpage.js
1.  Added another condition in the if statement in opdetailPage.js  line 138
The problem was in line 138 the if statement doesn't check for me field. In public page, if user is not logged in me field will have value false instead of object.
=> Fix server crash when click on opportunity for not logged in user

components/VTheme/IdLine.js, pages/person/persondetailpage.js
1. add try/catch block around data getters in persondetailpage get initial props as this was throwing an exception when 403 forbidden was returned for non signed in users.  
Page later forces authorisation but getinitialprops runs early server side when we have not checked we are signed in.
Also reverted IdLine back to the way it was as we were getting DOM warnings a in a and p in p. Also the control contained static text - Legitimate Organisation.
=> VP-472 catch 403 forbidden is returned. fix idline

pages/home/home.js, server/api/health/health.controller.js
Fix api security backdoor to get information about the config file in api health check😀
1. Casl check for the api request if the request has the right to manage person then the request can return config file otherwise it will return normal message
=> Fix security api health config expose AWS key

components/Person/PersonCard.js, components/Person/__tests__/PersonCard.spec.js
VP-517 modify PersonCard to use VTheme Card
1. Remove <div> tag in PersonCard and use <Card> from VTheme to display people
2.  Use style tag in PersonCard to wrap overflow text in person's name
3.  Update testcase
=> VP-517 modify PersonCard to use VTheme Card

lib/__test__/apiCaller.spec.js, lib/apiCaller.js
VP-202 api caller triggers onfulfilled callback insetad of onrejected callback when fetch fails
1.  Updated to return a Promise.reject in catch block.
2.  Update to return a Error in Promise.reject 
3. 
=> VP-202 api caller triggers onfulfilled callback insetad of onrejected callback when fetch fails

server/server.js, x/aws/deploy-beta
1.  remove usage of git-describe in startup server.js as this appears not to work on the fargate servers. 
2. 
3. 
=> VP-582 revert git-describe usage.

__tests__/landing.spec.js, components/Op/OpCard.js, components/Op/__tests__/OpCard.spec.js
- 
- [ ✔] Run `npm test` and all the tests pass.
- [✔ ] Run `npm run lint` and there are no warnings.
- [ ✔] Not decreased the overall test coverage?
- [✔ ] Included the Jira ID and description in the PR title
1. Update OpCard to use VTheme to render Ops and remove inline styles
2. 
3. 
=> VP-516 rewrite the op card to use v theme card and simplify all the styling

components/Act/ActDetailForm.js, server/api/activity/__tests__/activity.spec.js, server/api/activity/activity.js
1.  Made name required in activity.js
2. its already required in the form.
3. stopped hiding the required * indicator on the form
4. made duration not show an error when page first loaded.
5. removed deprecated title field.
=> VP-569 make activity name mandatory

components/Act/ActDetailForm.js, package-lock.json, package.json, server/api/activity/__tests__/activity.spec.js, server/api/activity/activity.js, server/api/person/__tests__/person.spec.js, server/services/helpers.js
1.  Throw 500 error for any mongoose validation error instead of 200 error
2. Change default image url path for activity schema 
3. Remove git-describe package since we are not using it
=> Fix activity db validation handler (VP-763)

assets/voluntarily.less, components/Header/HeaderMenu.js, components/Navigation/Navigation.js, components/__tests__/Header.spec.js, lib/sec/__test__/actiontoken.spec.js, lib/sec/actiontoken.js, lib/sec/keys.js, pages/api/token/[cmd].js, pages/api/token/index.js, pages/api/token/token.js, pages/auth/sign-thru.js, pages/test/test-token.js
1. test/test-token page asks api for an action token. clicking the token link hits a page that validates the token link, carries out the requested action and then forwards the to the redirected page.
2. if person using link is not signed in they go through a sign in process
3. add sign-thru.js a neater way to carry a destination through the sign in process.
This function will be used to generate emails containing self-registration links.
/test/test-token
=> VP-795 handler page for action tokens

package.json
When tests fail this will ensure ava displays the correct line of the
error in the unit test.
1. Set the "retainLines" config value in the ava config so that unit test errors are accurate
When running ava tests that fail they were showing the wrong line, e.g. (line 28 is highlighted below)
```
/home/node/app/server/api/school-lookup/__tests__/school-lookup.spec.js:28
27:   const requiredFields = SchoolLookUp.schema.requiredPaths(true)
28:                                                                 
29:   const error = await t.throwsAsync(SchoolLookUp.create({}))    
Test failed via `t.fail()`
```
After this config change the output looks like this:
```
/home/node/app/server/api/school-lookup/__tests__/school-lookup.spec.js:19
18:           
19:   t.fail()
20:           
Test failed …
```
=> Configure ava to retain lines

components/VTheme/NumericRange.js, components/VTheme/__test__/NumericRange.spec.js
1. There is a bug because the value field of the InputNumber component wasn't being set. Users could use this component to physically type into, but it wouldn't re-load values after page reload.
2. 
3. 
=> VP-823 Set value field of the InputNumber component

emails/inviteSchool/html.pug, emails/inviteSchool/subject.pug, emails/theme/footer.pug, lib/sec/actiontoken.js, lib/sec/keys.js, server/api/school-invite/__tests__/school-invite.controller.spec.js, server/api/school-invite/school-invite.controller.js, server/api/school-invite/school-invite.routes.js
1. Add API to send school invitation email
Still more work to do on handling clicks on the magic button in the email but this is the first step.
=> VP-871 Add API end point to send school invitation emails

server/api/goal/__init__/goal.init.js, server/api/member/__tests__/findMy.spec.js, server/api/member/findMy.js, server/api/member/member.controller.js, server/api/member/member.routes.js
These changes support Goal Card links to key places 
1. Adds a new pseudo page URL /my where 
/my/org  goes to the first org of which I am a member
/my/org/:category goes to the first org I belong to that is of that type e.g /my/org/op goes to my school
/my/person goes to my profile page. 
2. new routes added to members.routes as this is closest to what we are checking but new functions added to findMe.js. 
These all check the person is signed in, get their membership records and find the relevant organisation, then redirect to the correct url for that page e.g /orgs/1231232131
=> VP-879 Add /my/org/op call to redirect to my school

.cirrus.yml, package.json
1. Turn off nyc "all" config by default and add a script that turns it on for continuous integration test runs.
=> VP-883 Add test-all script for CI test runs

__tests__/oplistpage.spec.js, pages/op/oplistpage.js
1.  We don't have to use classes for top level pages, you can use functional components and still have a getInitialProps call as illustrated here.
2. Also the test files for top level pages don't have to be complex and load everything. This example mocks dispatch and provides the resulting props to the component.
3. using shallow rendering means the test is fast and only needs to check the high level component positioning, given that the individual components should have their own unit tests.
This page is available on the route /op  and /ops  the first as it is the index page for the /pages/op folder and the second due to a specific path listed in routes.js
=> VP-888 demonstrate functional component page with GetInitialProps

.cirrus.yml, package-lock.json, package.json
1. Install `webpack` as a dependency so prod-docker build works
I've tested this locally by mimicking what happens during the prod-docker build (specifically, setting `NODE_ENV` to "production" and passing the `--production` flag to `npm ci` and then running `npm run prod-build`).
=> VP-904 Fix broken production build

.cirrus.yml, server/api/personalGoal/__tests__/personalGoal.subscribe.spec.js
The task was consistently being killed on Cirrus due to running out of
memory. Given this doesn't seem to happen to our prod docker task I've
switched our the build test task to be a docker builder instead.
1. Switch "build test" Cirrus task to be a docker builder instead (hopefully to avoid the task being killed by Cirrus due to running out of memory)
=> VP-904 Switch task to docker builder

components/Goal/GoalCard.js, components/Goal/GoalGroupHeading.js, components/Goal/GoalSection.js, components/Goal/__tests__/GoalCard.spec.js, components/Goal/__tests__/GoalGroupHeading.spec.js, components/Goal/__tests__/GoalSection.spec.js, pages/admin/goals.js, pages/api/notify/org/action.js, pages/api/xadmin/assignPersonalGoals.js, server/api/goal/__init__/goal.init.js, server/api/goal/__tests__/goal.fixture.js, server/api/goal/__tests__/goal.spec.js, server/api/goal/goal.js, server/api/goal/goalGroup.js, server/api/member/__tests__/member.controller.spec.js, server/api/member/member.controller.js, server/api/member/member.lib.js, server/api/organisation/organisation.js, server/api/personalGoal/GoalTests.js, server/api/personalGoal/__tests__/GoalTests.spec.js, server/api/personalGoal/__tests__/personalGoal.lib.spec.js, server/api/personalGoal/__tests__/personalGoal.subscribe.spec.js, server/api/personalGoal/personalGoal.lib.js, server/api/personalGoal/personalGoal.subscribe.js, server/api/school-invite/__tests__/school-invite.controller.spec.js, server/api/school-invite/school-invite.controller.js, server/services/pubsub/topic.constants.js
1. goal category renamed to goal.group and init from constants
2. pubsub message sent when new OrgAdmin member created
3. pubsub handler adds cards to new OrgAdmin member to setup the school
* changes to the data format for a goal means the existing goal collection must be removed and re-instated.
* Testing the pubsub is achieved by publishing another message in the handler and watching for this in the test. means we don't have to add any wait loops.
* needs some more testing
=> VP-898 publish new school orgadmin event and trigger Goal Cards

package.json
1. The server needs to be restarted to reflect updates to lang/*.json files but this doesn't happen automatically in dev environments at the moment. This change configures nodemon to also watch the lang directory so those changes will show up without needing to manually restart the server.
=> VP-912 Setup nodemon to watch lang directory

__tests__/op/opdetailpage.spec.js, pages/op/opdetailpage.js
1. Added a function that would set orgAdmin status to either true or false 
2. 
3. 
=> Added function to set OrgAdmin value dynamically

__tests__/404.spec.js, components/Interest/__tests__/InterestItem.spec.js, components/VTheme/__tests__/ItemList.spec.js, pages/_error.js
1. Fix errors relating to React Intl not being able to find the intl object
For the fixes to the `ErrorPage` I first attempted to make it extend the `IntlDocument` (from `pages/_document.js`) but this didn't give the results I was hoping for and generated lots of errors. It seems like what gets passed to `getInitialProps` is different for `_error.js` compared to `_document.js` (e.g. `context.renderPage` was not available in `_error.js`). This is why I went with the approach you can see in these changes (using the `IntlProvider` where appropriate in `_error.js`).
=> VP-939 Fix react intl error messages

components/Person/__tests__/PersonBadge.spec.js
1. Fix a deprecation warning that was being generated while running unit tests
Enzyme has deprecated use of isEmpty and recommend using exists instead.
There is a brief discussion of the deprecation here: https://github.com/airbnb/enzyme/issues/705
=> VP-943 Use exists instead of isEmpty

components/Person/PersonDetail.js, lib/__tests__/urlUtil.spec.js, lib/urlUtil.js
=> VP-942 Automatically prefix http to a profile website url if no scheme is supplied

.gitignore, x/atlas/alpha-dump, x/atlas/alpha-restore, x/atlas/beta-dump, x/atlas/beta-restore
1. add scripts to x/atlas to dump and restore test databases vly-alpha and vly-beta
2. used script to move data from vly2-alpha to vly-alpha to make db names consistent
3. added dump folder to .gitignore so that backups are not put into git.
=> VP-951 dump and restore alpha and beta databases

x/aws/deploy-beta
1. Deploy beta script now pulls from the alpha repo tags and pushes again.
2. 
3. 
There is probably an AWS API call that could be called to retag the image without having to pull and push it. 
=> VP-951 update deploy-beta to use southeast-2 Repository

pages/home/home.js
The title of the Goals Section is taken from the group of the first card in the list.  This allows the section title to gradually change from Getting Started to new things to do as the goals progress. 
The user has a feature where they can click on the (x) in the top right corner to hide a card for a week. While hidden cards are not drawn they are still in the list and affect the section title.
This change removes hidden personal goals from the list when preparing them for display. 
=> VP-911 remove hidden goals from GoalSection data

server/api/member/__tests__/findMy.spec.js, server/api/member/member.lib.js
When a person visits /my/org they are redirected to the organisation they belong to.
If they belong to more than one organisation we want to ensure that they are routed to the 'most important' of the choices. first priority is given to orgs for which the person is OrgAdmin, then Membership then followers. 
This is achieved by sorting the members list returned for the person by membership status.
=> VP-884 my/org puts admins first

server/api/personalGoal/__tests__/personalGoal.lib.spec.js, server/api/personalGoal/__tests__/personalGoal.spec.js, server/api/personalGoal/personalGoal.constants.js, server/api/personalGoal/personalGoal.js, server/api/personalGoal/personalGoal.lib.js
1.  Once a personal goal passes the evaluation test it is marked as 'COMPLETED'.  The completed goal is still visible to the person and has a 'trophy' icon superimposed.  Once the goal has been completed for more than 7 days the state is changed to CLOSED. Closed goals are not displayed and will disappear from the goals tray.
=> VP-893 hide goal cards once completed and seen

lib/auth/auth.js
1. Fix a bug where people signing in with email addresses of the form name+name@domain.co.etc. would not be found in the database (due to the + being interpreted as space). 
The fix is to correctly URI encode the query parameters containing the email address.
=> fix signin for emails containing + char

__tests__/person/persondetailpage.spec.js, lib/auth/auth.js, pages/person/persondetailpage.js
1. The /person/id page shows a persons profile independently of the home page.  This is visible to all people and is their public profile.  This page can be edited by Admins, OrgAdmins and the person themselves.  A missing test meant that people could not edit their own profile on this page. 
This change makes the edit button available to people and also adds a full unit test for the persondetailpage.
This is important as this page is the one linked to by the Complete your profile goal card.
=> VP-959 My Profile page has an edit button

server/api/goal/__init__/goal.init.js, server/api/goal/__tests__/loadGoals.spec.js, server/api/interest/__tests__/interest.lib.spec.js, server/api/interest/interest.js, server/api/interest/interest.lib.js, server/api/person/__tests__/person.spec.js, server/api/personalGoal/GoalTests.js, server/api/personalGoal/personalGoal.controller.js
New volunteers after first signing in are given the getting started collection of cards. This includes Find your first activity. The start button on the card links to the search page.  
The evaluation of the card is true when the person has clicked i'm interested on a card.  i.e. it passes so long as there is any interested record for the person. 
This doesn't wait for the person to commit or carry out a volunteering activity.  But it will be sufficient to get the first activity into the home page.
=> Vp 781 create find first opportunity goal

components/Org/OrgBanner.js, components/Org/OrgCategory.js, components/Org/__tests__/OrgBanner.spec.js, components/VTheme/Profile.js, pages/org/orgdetailpage.js
1. Move website link from banner as it already appears in the contact details block below the tab line. Also we don't want to encourage people to leave the site.
2. Restrict the height of the image to 12rem as this controls the overall height of the banner.  keep the images about 16/12 (4/3) aspect ratio.
3. Move the Org Type icon to just in front of the org name. 
4. When page is edited and then saved set a saved state var and show the return home button. 
This button will remain visible until the page is clean loaded.
=> VP-828 remove website from banner, add return home btn

package-lock.json
1. run npm audit fix to update package-lock so that a high risk library gets updated.
=> VP-977 update package-lock to remove warnings

components/Act/ActDetailForm.js, components/Op/OpDetailForm.js
- [✔ ] Run `npm test` and all the tests pass.
- [✔ ] Run `npm run lint` and there are no warnings.
- [✔ ] Included the Jira ID and description in the PR title
1. Activity provider and requestor cannot put long titles when creating a new request and activity.
=> VP-807 Limit text input length for Activity and Opportunity forms

__tests__/home.spec.js, __tests__/op/opdetailpage.spec.js, components/Op/OpAboutPanel.js, components/Op/OpBanner.js, components/Op/OpCloseOpportunity.js, components/Op/OpTabs.js, components/Tags/TagDisplay.js, components/examples/UseRouter.js, components/examples/__tests__/UseRouter.spec.js, pages/home/home.js, pages/op/opdetailpage.js, pages/test/test-router.js
On the Opportunity Detail page when you switch tabs the URL is updated with ?tab=manage etc. 
This means that the location can be bookmarked, visited directly and reloaded keeping the same page. 
updated components use useRouter instead of withRouter. This requires a change to the way the router is injected in unit tests.   New way is to use sinon to override useRouter with a mock router - this is cleaner and easier to use.
=> VP-885 bookmarkable tabs and useRouter tests

package-lock.json, package.json
1. Replace `rm -rf` with `rimraf` for windows support
=> VP-974 Replace `rm` with `rimraf` in tests

server/api/member/__tests__/member.lib.fixtures.js, server/api/member/__tests__/member.lib.spec.js, server/api/member/member.lib.js
1. Remove the sort function compareMemberStatus
2. Split member records into separate arrays based on the status fields recombine with important member status records at the top
This change fixes an issue that causes the code coverage percentages to change between test runs.
=> VP-1045 Refactor findOrgByPersonIdAndCategory to remove variable code coverage results

server/api/person/__tests__/person.spec.js, server/api/person/person.js
1. Add a new field to the person schema to track whether or not a person wants to receive email notifications from Voluntarily. The field is a required boolean field that defaults to true (opted in to notifications).
This flag will be used to decide if we send the user email notifications. VP-1041 will add the ability to update this flag on a person's profile, VP-1042 will update any existing emails to respect this flag when deciding whether or not to send an email notification
=> VP-1040 Add sendEmailNotifications flag to person

components/Interest/InterestArchivedSection.js, components/Interest/InterestSection.js, components/Interest/RegisterInterestSection.js, components/Interest/__tests__/RegisterInterestSection.spec.js, components/Op/OpVolunteerInterestSection.js, pages/op/opdetailpage.js
Cause is opsdetailpage loading interested list. placing entire op into query instead of opid.  which blows out the URL and returns a 413 having no interested record causes the page to show the button.   Side effect is that we can create multiple records.
Fix is to replace op with op._id  when api/interests/?op called in RegisterInterestSection.js:30
The interested records are pulled down by the client after the page loads - in RegisterInterestSection. i.e. its acting independently.  This means that for a second the control does not show the right interested button.  
Changed props to the component so that it does not show anything if the data is not provided. and shows loading indicator if data is not synced.
=> VP-1102 Activity which volunteer showed interest before RESETS BACK and allows to add another interested record

components/Interest/RegisterInterestSection.js
when the Get Involved button is pressed a new interested record is sent to the server. This was missing the opportunity id as a previous change changed the property name to opID instead of op. 
I missed this point of use.
As a result the save of the interested record fails validation and an error is returned. The page returns to the original state.
=> use opID prop instead of op.

lib/redux/reduxApi.js, server/middleware/session/__tests__/setSession.spec.js, server/middleware/session/setSession.js
1. Case sensitivity in the Authorization header used by API calls caused the idToken to not be recognised when handling server side API calls. This resulted in the person appearing to be not signed in and an ANON session being created. which in turn refused permission to allow a person to get their own data. 
The correction is to make all uses of Authorization headers lower case. 
From RFC 2616 - “Hypertext Transfer Protocol -- HTTP/1.1”, Section 4.2, “Message Headers”:
Each header field consists of a name followed by a colon (“:”) and the field value. Field names are case-insensitive.  
However somewhere along the line the header was being lowercased.
=> Vp 1221 getinitprops for home returning 403 forbidden on s

__tests__/person/persondetailpage.spec.js, components/Person/PersonDetail.js, pages/home/home.js, pages/person/persondetailpage.js, server/api/goal/__tests__/goal.fixture.js, server/middleware/session/setSession.js
1. recent changes to the home and person detail pages resulted in the pages displaying an API fetched person(meid) instead of as previously using the session.me value.  This because session.me now does not include any personal or private data for the person and only id and role info.   However, the lines to associated current membership with the person were still updating the me variable. This has been changed to that orgMembership and orgFollowership are now attached to the person.  Once this is done the personDetail membership sidebar updates correctly. 
Also changed some of the complex flow in home.js factored out the NoPersonAvailable component. and return early from render once the output is known.  This reads more clearly and avoids executing code that is not needed.
Also added …
=> Vp 1226 persondetailpage not showing membership

components/IssueBadge/issueBadge.js
1. add try catch block around setAvailableBadgeData to handle error returned if the Badgr server is not available or if the platform has not set access credentials.
error was visible only on person detail page when signed in as admin so that the Add Badge button was present.
=> VP-1229 catch errors in badge api if server not available

server/api/organisation/__tests__/organisation.permissions.spec.js, server/api/organisation/organisation.controller.js
1. Only ADMIN role can set the category of an organisation via the PUT /api/organisations API
2. 
3. 
=> VP-1229 Only ADMIN role can set the category of an organisation #630

package-lock.json, package.json, server/api/image/__tests__/image.spec.js, server/services/image/__tests__/imageResize.spec.js, server/services/image/imageResize.js
The imageResize function is replaced with a null passthrough and the sharp library is removed from the build. This is because. linux-x64' binaries cannot be used on the 'linuxmusl-x64
removing the feature means that uploaded images will not be optimsed for size and the small and large versions will both be large versions.  This increases storage requirements and download time. 
However this just puts us back where we were a week ago.
=> remove imageResize for now

server/api/interest/interest.controller.js, server/api/member/member.controller.js, server/api/member/member.lib.js
The sendEmailNotifications flag was added to person schema to track whether the person has unsubscribed from emails.  This data is sent when a GET request is performed on a person. However, the interested email process uses the person record populated into the interest record clicked by the person.  This populate out did not include sendEmailNotifications. 
By adding sendEmailNotifications whenever a person reference is populated out that includes the email address we ensure that sendEmail respects the settings
2. 
3. 
=> VP_1223 ensure sendEmailNofifications is included in interest and member details

x/aws/deploy-delta, x/aws/deploy-gamma
the deploy scripts were still referencing the singapore docker repository. They now reference the sydney repo.
=> VP-1269 deploy to gamma and delta scripts updated for new repository location

lib/callApi.js, package-lock.json, server/api/tag/__tests__/tag.spec.js, server/api/tag/tag.ability.js, server/api/tag/tag.constants.js, server/api/tag/tag.controller.js, server/api/tag/tag.js, server/api/tag/tag.routes.js, server/middleware/authorize/authorizeRequest.js
Access to the Tags API is now controlled by Role Based Access Permissions. 
see : https://voluntarily.atlassian.net/wiki/spaces/VP/pages/18677761/API+Access+Security+Rules
Anon people - cannot access tags
Authorised people - can read and list tags but not create or change them
Admins - can perform all CRUD actions.
The tags word list collection feature is only partially implemented.  There is currently a single word list (tags) that is used for all tagging activities. It is read by edit forms that want to autocomplete new tag fields.  It is not updated through the API but is updated when a person saves a profile, activity or opportunity containing new tags. 
Admins have full crud access in order to allow the future tidying up of the tag lists.
=> add CASL abilities to tags

hocs/securePage.js, server/api/personalGoal/__tests__/personalGoal.ability.spec.js, server/api/personalGoal/__tests__/personalGoal.spec.js, server/api/personalGoal/personalGoal.ability.js, server/api/personalGoal/personalGoal.constants.js, server/api/personalGoal/personalGoal.controller.js, server/api/personalGoal/personalGoal.js, server/api/personalGoal/personalGoal.routes.js, server/middleware/ability/getAbility.js, server/middleware/session/setSession.js
Personal Goals API calls are protected by CASL rules
Anon users cannot access personalGoals.
Signed in users can read their own goals but only change status
admin users can read and write personalGoals. - This allows support to fix problems.
=> Vp 1093 personal goal api permissions management casl

__tests__/admin/invite-school.fixture.js, __tests__/admin/invite-school.spec.js, pages/admin/invite-school.js, server/api/school-lookup/__tests__/school-lookup.ability.fixture.js, server/api/school-lookup/__tests__/school-lookup.ability.spec.js, server/api/school-lookup/school-lookup.ability.js, server/api/school-lookup/school-lookup.constants.js, server/api/school-lookup/school-lookup.routes.js
1. Add permissions for school lookup API
2. Fix bug in school invite page where cookies were not being sent along with API request (when run server side)
=> VP-1095 School lookup API permissions

server/api/activity/__tests__/activity.spec.js, server/api/opportunity/__tests__/opportunity.spec.js, server/api/organisation/__tests__/organisation.fixture.js, server/api/organisation/__tests__/organisation.permissions.spec.js, server/api/organisation/__tests__/organisation.spec.js, server/api/organisation/organisation.js, server/api/school-invite/__tests__/school-invite.controller.spec.js, server/api/school-invite/school-invite.controller.js
A school-invite email contains a token that when used creates a new organisation based on the school id and adds the person as an admin. 
The handler did not check whether the invite had already been used and the organisation created, as none of the fields is required to be unique the second create succeeds and we get two schools with the same name but different ids.  Thus each user of the token gets their own school.
This change uses the slug field to check whether the school already exists. if so it returns the original school. 
The schema is changed so that two organisations cannot have the same name or slug. attempts to create an organisation with the same name as an existing one, or to edit the name of an organisation to be the same should fail.
=> VP-1312 - Avoid duplicating the organisation if school-invite used twice.

emails/theme/footer.pug, emails/welcome/html.pug, emails/welcome/subject.pug, server/api/person/__tests__/person.subscribe.spec.js, server/api/person/person.email.js, server/api/person/person.subscribe.js, server/services/pubsub/topic.constants.js
Send a Welcome email to a new person when they first sign in. 
When a person signs in for the first time a new account is created.  AddPerson publishes a TOPIC_PERSON__CREATE event which is received by person.subscribe. This generates a new email to the person using the Welcome template.
This, in turn, generates a TOPIC_PERSON__EMAIL_SENT event.
=> VP-1070 initial sign up email

server/api/interest-archive/__tests__/interestArchive.ability.fixture.js, server/api/interest-archive/__tests__/interestArchive.ability.spec.js, server/api/interest-archive/interestArchive.ability.js
1. Update permissions for volunteers (and other authenticated users) when listing/reading from the interest archive API (volunteers can read/list their own archived interests)
=> VP-1338 Interest archive API permissions

__tests__/op/opdetailpage.spec.js, __tests__/org/orgdetailpage.spec.js, components/Member/RegisterMemberItem.js, components/Member/RegisterMemberSection.js, components/Member/__tests__/MemberSection.spec.js, components/Org/OrgTabs.js, components/Org/__tests__/OrgTabs.spec.js, pages/op/opdetailpage.js, pages/org/orgdetailpage.js
1. The organisation details page was already factored into  OrgTabs, OrgBanner etc. However, it did not set the current tab in the URL making it bookmarkable.  This change captures tab changes and updates the url.  
2. The edit button is moved from the banner to an edit tab and only shown to admins
3. Anon people only see the about tab.
4. fixed flash of unwanted buttons on page load.  VP-1336 by correcting the type of me._id from object to string when comparing membership.
=> VP-973 make org tabs bookmarkable as for op tabs

x/db/make-admin.js
1. Adds a command line script that takes an email address as an argument and attempts to find that person record and give it the admin role.
This is intended for use in local development environments - at the moment it's quite hard to make yourself an admin (the person API prevents a standard user from setting their role to "admin", so editing roles on your profile does not work).
=> VP-1345 Add script to make person an admin

server/middleware/session/__tests__/setSession.fixture.js, server/middleware/session/__tests__/setSession.spec.js, server/middleware/session/setSession.js
1. Clear the idToken cookie if the JWT is found to be expired
I've been finding that when I start work in the mornings on Voluntarily my JWT is always expired and I have been having to jump through hoops to sign back in (usually either clicking the "Sign out" button and then signing in again, or clearing my cookies before attempting to sign in). If I don't do this and just click "Sign in" straight away the first page I viewed would appear to be signed in successfully but as soon as I navigate to a different page I was ending up back in the signed out state.
This change removes that frustration - the first request after the JWT expires will now clear the idToken cookie and clicking on "Sign in" will sign you in as expected.
=> VP-1350 Clear idToken cookie on JWT expiry

server/middleware/session/__tests__/jwtVerify.spec.js, server/middleware/session/jwtVerify.js, x/get-dev-id-token.js
1. When NODE_ENV is development allow self generated idTokens to be used for authentication, the benefits of allowing this are:
- makes testing expired tokens significantly easier
- makes it easy to test features by imitating logins for certain accounts
- removes the need for Auth0 from the authentication process so could make future automated end-to-end tests easier to write
=> VP-1359 Allow use of dev generated idTokens

pages/home/home.js
home.js getInitialProperties makes eight reduxApi calls to obtain all the data it needs from the database. These are wrapped in Promise.All so they can run in parallel.  When running server side if any call throws an exception then the page response will be sent to the client before all the data is available. 
using allSettled waits for all the calls to resolve whether they fail or not. 
This means that failure to obtain one set of data e.g. the interests list will not block the rest of the page. Coupled with the <Loading > component that shows API call errors makes it easier to see the cause of the problem
Promise.allSettled is a recent addition to the language 
https://javascript.info/promise-api#promise-allsettled
we should use a polyfill, or babel should be configured to provide the …
=> VP-1321 replace Promise.All with allSettled so we get as much data as possible.

server/api/interest/__tests__/interest.ability.fixture.js, server/api/interest/__tests__/interest.ability.spec.js, server/api/interest/interest.ability.js
1. Add test for interest API - volunteer with no interests receives 200 with empty array
=> VP-1365 Add test for volunteer with no interests

components/Person/PersonDetailForm.js
1. If the frontend has a role which the API does not allow, then the user cannot save their profile. 
e.g. If the current user is an org admin, then their person object will have the orgAdmin role, but this cannot be sent to the server so it needs to be trimmed before sending
2. 
3. 
=> VP-1375 Only send applicable roles when saving a profile

server/api/interest/__tests__/interest.ability.fixture.js, server/api/interest/__tests__/interest.ability.spec.js, server/api/interest/interest.controller.js
Implement permissions around interest status transitions for the interest API. Primarily this applies to people with the "volunteer" role who should only be able to update status from:
- "invited" -> "committed"
- "committed" -> "interested"
=> VP-1323 Volunteer interest update

server/api/person/__tests__/person.permissions.spec.js, server/api/person/person.controller.js
1. Return 'sensitive' personal details of a user (via /api/people/:id) if;
1.1 the requested user is in the current user's organisation (e.g. we both work for New World)
1.2 or, if the requested user is on an opportunity the current user is running. This fixes the case where someone running an op clicks on a person who has shown interest to see that person's personal details (email, phone number, education, job, location, place of work)
2. 
3. 
=> Feature/vp 1380/personal details org invited

package.json
1. Remove ProjectDemo.wiki as it was breaking the storybook deploy
2. Change start script to allow static imports from public directory
3. This PR is required to enable component library deployment
=> VP-465 setup storybook deployment

components/Interest/RegisterInterestItem.js, components/Interest/RegisterInterestSection.js, components/Interest/__tests__/RegisterInterestSection.spec.js, server/api/interest/__tests__/interest.ability.spec.js, server/api/interest/__tests__/interest.spec.js, server/api/interest/interest.controller.js, server/api/interest/interest.js
the termsAccepted flag in the interest schema indicates that the person in the record has accepted the terms and conditions.  This now defaults to false internally. 
Any API call to POST new interest must set termsAccepted to true or it will be rejected 403. forbidden. 
The RegisterInterestSection component creates a new interest when the "Get Involved" button is clicked. This shows the popup message editor with the terms message showing, clicking ok accepts the terms.  So the handler now adds termsAccepted: true to the posted request.
Subsequent users of the message editor will hide or show the terms lines depending on the value of termsAccepted.  
Note for some previously created interest records this field will be false and the message will show. However the state is not updated on PUT …
=> VP-1403 termsaccepted is not being saved 

lib/auth/__tests__/auth.spec.js, lib/auth/auth.js, lib/urlUtil.js, server/middleware/session/setSession.js
1. Client side redirect to sign-thru also triggered the server side setSession redirect, causing several redirects to stack up. Giving the feeling of a 'loop'.
2. The end outcome of the client side redirect wasn't working correctly because of a typo in getPathAndHash
3. Next router Router.replace would crash the browser and cause an infinite loop. window.location.replace worked perfectly.
=> [VP-1413] Fixes several issues with client side redirect to sign thru

components/Op/OpStatus.js, components/Op/__tests__/OpStatus.spec.js
OpStatus is used to generate a translated string showing the current opportunity status. e.g. Draft, Active etc.  
An instance where this is called with no status causes a 500 error exception on alpha. This change ensures that the line returns null instead of exception when that happens.
=> VP_1419 - Quick Fix. protect OpStatus from empty state

server/middleware/session/__tests__/setSession.spec.js, server/middleware/session/setSession.js
When setSession on the server detected an expired JWT idToken it responds to the page request with a redirect to the sign-thru page to cause a new sign in to occur.  This was returning a 301 permanent redirect. so when the sign in was completed it would try to reload the original url which would use the cached redirect to sign-thru again.  causing the loop.
changing this to a 302 temporary redirect means that the browser will retry the original page correctly when sign-in completes.
=> VP-1413 Fix sign in oscillations when token expires

components/Op/OpAboutPanel.js, server/api/archivedOpportunity/__tests__/archivedOpportunity.ability.spec.js, server/api/archivedOpportunity/archivedOpportunity.ability.js, server/api/opportunity/__tests__/opportunity.ability.spec.js, server/api/opportunity/opportunity.ability.js, server/api/opportunity/opportunity.constants.js
API security filter was removing the requestor and offerOrg from an opportunity when being obtained for a VP or anon person.  This prevents the page from displaying correctly and does not tell the potential volunteer crucial information for their decision.  (Feedback from testing).
This change makes the list of fields made public clearer by placing them once in the constants file and using consistently.
=> Vp 1421 show volunteers organiser and offer org of the opportunity

components/Act/ActDetail.js
1. The document icon next to each document on an activity looks broken on some computers. So for now I'll just remove the icon and we can decide later what or if an icon could go there
2. 
3. 
=> VP-1432 Remove PDF unicode icon next to each document

components/Op/__tests__/Op.fixture.js, server/api/archivedOpportunity/__tests__/archivedOpportunity.fixture.js, server/api/archivedOpportunity/archivedOpportunity.controller.js, server/api/opportunity/__tests__/opportunity.fixture.js, server/api/opportunity/__tests__/opportunity.spec.js, server/api/opportunity/opportunity.constants.js, server/api/opportunity/opportunity.controller.js, server/api/opportunity/opportunity.js, server/api/opportunity/opportunity.routes.js, x/db/perf/makeOps.js
Add a 'type' field to the opportunity schema.  has values of OpportunityType.ASK or OpportunityType.OFFER.  note this is an enum not a bool as we might have other types. 
it is a required field with a default of ASK so this will preseve all existing behaviour.  
Tests update to check we can read and write the types. 
Ability and default list of fields updated to ensure type is always sent out.
fixtures updated.
When writing clients if type is not available then assume it is ASK.
=> VP-1479 - Add type = ask or offer to opportunity + test

components/Op/OpType.js, components/Op/__tests__/OpType.spec.js, lang/en.json
Adds components <OpType type={op.type} > that will write Ask or Offer text on the page.
Also OpTypeStamp which will place a large stamp over the picture - as per Draft.  this might not be needed.
=> Add OpType and test

server/api/activity/activity.routes.js, server/api/opportunity/opportunity.routes.js, server/api/organisation/organisation.constants.js, server/api/organisation/organisation.controller.js, server/api/organisation/organisation.js, server/api/organisation/organisation.routes.js, server/api/person/person.routes.js, server/api/tag/tag.constants.js, server/util/__tests__/initTags.spec.js, server/util/initTags.js
To InitTags we add a second named tag list for Groups.  This will hold tags used by orgs to group topics together for searching.
To organisation.js we add a new groups [string] that will hold one or more groups. usually just one. e.g. Business, School, Personal
To the controller we update any incoming group tags into the taglist. 
The getOrganisation call is renamed listOrganisation and a default select is used to limit the size of the result to those fields used in OrgCards.  The fields are now in constants.
=> VP-1500 add group tags to org schema

__tests__/home.spec.js, components/Op/OpAdd.js, lang/en.json, pages/home/home.js
Home page button now only has one choice - Ask or Offer which leads to the resources page. This means you have to first consider using an existing template before creating a new thing. 
On the templates page we will add placeholder templates for Generic thing.
=> Tidy up home page buttons

components/Navigation/Navigation.js, lib/useWindowSize.js
- [] Not decreased the overall test coverage?
1. When the screen width falls below 765 we switch from the horizontal menu to a vertical submenu with a '☰' 
2. Added a useWindowSize hook to detect size changes.
3. 
normal
=> VP-1607 useWindowSize hook and vertical menu

__tests__/api/reports/summary.spec.js, pages/api/reports/summary.js, pages/reports/summary.js
- [?] Not decreased the overall test coverage?
1. Adds `/api/reports/summary` endpoint. This returns MongoDB collection counts for acitvity (scoped by status = active), interest 
2. Adds `/reports/summary` page that consumes the endpoint above to present the summary data in a very simple UI.
I have written a unit test for the summary API handler based on the health API. I also attempted to write unit tests for the page, but had trouble figuring out how to convince the test that an administrator was signed in. I attempted to borrow some test setup functions from other tests, which got me into the world of attempting to set up a stub Redux state. It ended up feeling too complicated for the behaviour I was trying to test, but I _would_ like to get this test in if I can have some additional …
=> VP-1608: Basic reporting page with activity,interest, person and opportunity counts

.cirrus.yml, components/Header/Header.js, components/__tests__/Header.spec.js
When a person is signed in as an Admin or Tester the screen shows a purple line above the menu. This allows them to know when they should be more careful.
=> VP-1424 show purple line above menu for admins

x/db/copy-org-category-to-role.js
Update the script x/db/copy-category-to-role.js to remove the category field once the role field has been created and copied.
=> remove org.category after creating org.role

server/api/member/__tests__/member.lib.fixtures.js, server/api/member/__tests__/member.lib.spec.js, server/api/member/member.lib.js
When a person signs in we collect their role from the orgs they are members of.  If an org has VOLUNTEER_PROVIDER role add VOLUNTEER to the person's role.
This means that by default new people are not volunteers and cannot make OFFERS.  To do so they must first join a VP org.  this should happen automatically during onboarding when they are asked if they want to volunteer and for which group.
=> VP-1647 make person VOLUNTEER if they belong to a VOLUNTEER_PROVIDER

components/Act/ActTabs.js, pages/act/actdetailpage.js
on the Activity Detail Page
If person.role.includes(Role.VOLUNTEER) the default tab is asks. 
else default tab is offers.
Normal person sees
volunteer sees
=> VP-1655 default to asks tab for volunteers, offers tab otherwise.

components/Act/ActAboutPanel.js, components/Act/ActCard.js, components/Act/ActOpsPanel.js, components/Act/__tests__/ActCard.spec.js, components/Op/OpAdd.js, components/Op/OpCardSmall.js, components/VTheme/VTheme.js
Tidy up CSS on activity and small op card.
fix height and overflow of the cards so that they line up even if the text grows.
- worst case scenario the card will scroll internally.
=> VP-1659  CSS clean up on Activity and Op cards

.github/workflows/push.yml
This modifies the github workflow to correctly pass the ENV_SECRET during build step.
=> Modify alpha build step

SECURITY.md, components/Act/ActCardSuggest.js, components/Footer/Footer.js, components/Header/HeaderMenu.js, components/Interest/RegisterInterestMessageForm.js, config/clientConfig.js
1. Header menu help link now links to support.voluntarily.nz - zendesk rather than jira.
2. various links to knowledge base pages updated similarly.
3. 
=> VP-1753 change support links from jira to zendesk

.github/workflows/push.yml
each merge branch should only deploy its own version. 
i.e merge to beta deploys beta.
so remove the deploy to beta from the alpha build
=> VP-1752 remove beta push on alpha build

pages/act/actlistpage.js
1. visiting /asks results in a 500 error. this is the activities page visited with no specific /ask or /offer parameter.  In this case, we should default to asks.
=> VP-1767 if no type param default to ask

components/Act/ActDetailForm.js, components/File/FileUpload.js, components/Person/PersonDetail.js, components/Person/TopicGroupSection.js, components/Person/__tests__/PersonDetail.spec.js, components/SignUp/ChooseParticipation.js, components/SignUp/SelectTopicGroup.js, lang/en.json
1. Adds the topic group selection choices to the personal profile page.  these can be set without needing to edit the profile. - just click the ones wanted.
Next step is to use these settings in the discover tab
=> add topic group selection to profile

components/Member/__tests__/MemberSection.spec.js, components/Person/PersonRole.js, components/Person/__tests__/PersonRole.spec.js, components/VTheme/AvatarProfileLink.js, lang/en.json, server/api/interest/interest.controller.js
1. When we show a person's avatar (pic + name) this is now followed by an icon indicating their volunteer status (role).  
2. If the person has multiple roles we rank them and show the highest in order
basic, volunteer, orgadmin, help desk, admin
3. on hover a popover shows to list all the roles with icon and labels.
basic volunteer
admin
hover detail
=> Vp 1644 show volunteer status

components/VTheme/AvatarProfileLink.js, server/api/interest/interest.lib.js, server/api/member/member.controller.js, server/api/member/member.lib.js
1. The updated PersonAvatar now uses the role value to illustrate the volunteer status of a person. This role needs to be in the data obtained for both interests and membership lists.  the populate sections of these controllers did not include role so the component fails to display. 
2. also the component now checks if role is present before using it.
2. 
3. 
=> VP-1789 ensure people data have role included

docker-compose.yml
1. Exposes the default mongo port, allowing scripts and external browsers to connect.
2. Names `web` and `db` to something a bit more specific, in case devs have multiple docker containers to content with!
=> VP-1805: Expose mongo port, name containers

components/Act/ActAboutPanel.js, components/SignUp/SignUpInviteModal.js
1. Add a cancel handler to `SignUpInviteModal`, allowing it to be closed.
2. Show Ask/Offer help buttons if not logged in (per discussion with @avowkind )
=> VP-1785: allow signup modal to be cancelled

server/api/activity/__tests__/activity.lib.spec.js, server/api/activity/activity.lib.js
1. `getOpsForActivity` should not include DRAFT status ops in its count.
=> VP-1687: count only active ops

__tests__/admin/admin.spec.js, lang/en.json, pages/admin/index.js, pages/admin/test.js, pages/api/xadmin/runTest.js
1. Added a test button to the admin page
2. Added a button to the admin/test page to call external url to run automated tests.
=> VP-1726 add end to end test launcher to admin page

server/api/statistics/__tests__/statistics.fixture.js, server/api/statistics/__tests__/statistics.spec.js, server/api/statistics/statistics.controller.js, server/api/statistics/statistics.lib.js, server/api/statistics/statistics.routes.js
1. Implement `GET /statistics/summary` API endpoint to retrieve totalHours, totalVolunteers and avgHoursPerVolunteer for the last month/year for an organisation.
2. Implemented unit tests for the endpoint.
MongoDB aggregations are used for performance. The document graph can be queried in a single call to the database. Using populate and traversing the document graph would result in many calls to the database (`members X interests X opportunity`), which is grossly inefficient. 
The API schema is `GET /api/statistics/summary/:orgId/:timeframe` and returns an object similar to 
```json
{
"totalHours": 61.3,
"totalVolunteers": 5,
"avgHoursPerVolunteer": 12.26
}
```
=> VP-1842: Summary endpoint for the statistics API

server/api/statistics/__tests__/statistics.fixture.js, server/api/statistics/__tests__/statistics.spec.js, server/api/statistics/statistics.controller.js, server/api/statistics/statistics.lib.js, server/api/statistics/statistics.routes.js
1. Implement `GET api/statistics/locations` endpoint which retrieves the number of opportunity attendances by the organisation's volunteers at each location.
2. Implement `GET api/statistics/activityTags` endpoint which retrieves the weighted occurrences of each activity tag in the opportunities attended (see below for more info).
3. Unit tests added for each endpoint.
The same query from #1010 is used, so it retrieves stats for a specified org, within the specified timeframe. 
The locations API schema is `GET /api/statistics/locations/:orgId/:timeframe` and returns an object similar to:
```json
[
{"name": "auckland", "value": 2},
{"name": "wellington", "value" : 1},
]
``` 
This means there have been 2 opportunity attendances in Auckland and 1 in Wellington. 
**Note**: the location used …
=> VP-1842: Location and activity tag endpoints for the statistics API
