pages/index.js

Not sure if this is fixed elsewhere, but I needed this change to run on my system. Could of course also change the case of the folder the file is in.

Fix case on Landing page to match file system

---

CONTRIBUTORS

Added myself to the CONTRIBUTORS file.

VP-82 added Andrew Meads to CONTRIBUTORS file

---

docs/slideshows/developer_overview.md

- Added MongoDB installation link for Windows
- Added `git checkout` command in instructions for git.

Added more stuff to developer overview

---

Dockerfile
components/test/__tests__/IntlDemo.spec.js
config/config.js
docker-compose-prod.yml

There is still a lot of stuff that is probably not needed in node_modules, but this helps to cut the final production docker size a little bit.

Switch to slimmer production docker image with only built files

---

package-lock.json
package.json
server/api/opportunity/__tests__/opportunity.spec.js
server/api/person/__tests__/person.spec.js
server/server.js
server/util/test-memory-mongo.js

Fixed the problem by
1. replacing mockgoose in test-helpers with mongodb-memory-server in test-memory-mongo.  This runs a copy of mongo db with different ports and memory storage for each connection requested. It is also very fast.
BUT - the first time you run this it will download a binary of mongodb. so I don't know how well it will run on your system YMMV. and this will take a couple of minutes.
2. The server.listen line is not run in test mode.  This was the source of some of the weird exceptions. 
All the tests now pass and you can run multiple simultaneous instances of the same database test e.g. person.spec.js without errors.
@cyrus-raitava you will need to update your interested test to the new style.

VP-113 #comment fixed parallel test problem

---

CONTRIBUTORS

VP-82 Add Bill to CONTRIBUTORS

---

.travis.yml

DO NOT MERGE....just created PR to trigger travis build

VP-102: Add docker to travis build

---

components/Person/PersonCard.js
components/Person/PersonDetail.js
components/Person/PersonDetailForm.js
components/Person/PersonListItem.js
components/TestContainer/Container.js
hocs/publicPage.js
lang/en.json
lib/auth/__test__/auth.spec.js
lib/auth/auth.js
pages/person/persondetailpage.js
pages/person/personlistpage.js
pages/person/personupdatepage.js
pages/test-interest/test-interest.js
pages/test-interest/testy.people.js
pages/test.js
server/api/interest/__tests__/interest.spec.js
server/api/person/__tests__/emailperson.spec.js
server/api/person/__tests__/person.spec.js
server/api/person/email/verify/html.pug
server/api/person/email/verify/subject.pug
server/api/person/email/verify/text.pug
server/api/person/person.controller.js
server/api/person/person.js
x/db/andrew.person.json
x/db/dali.person.json
x/db/testy.people.json
x/db/testy.person.json
x/db/walt.person.json

mass rename of moniker to nickname - this reflects common usage across the Auth0 domain.
Also new creates a person document based on the auth record if the email is not in our database. sets up image from the picture provided and thats it.
We may need to reset existing people databases to reflect the changed schema.

rename moniker to nickname

---

CONTRIBUTORS

Neo branch

---

CONTRIBUTORS

Add my name to the CONTRIBUTORS file

Edited contributors file to add my name

---

lib/auth/auth.js
lib/redux/actions/index.js
lib/redux/reducers/index.js
lib/redux/reduxApi.js
pages/auth/signed-in.js

When the user logs in, add a session object to redux that captures their decoded JWT token, and their person object (if one exists).

Add session to redux

---

.cirrus.yml
Dockerfile
package.json

This will only run for master, and will push to alpha ECR tag as :master

Feature/vp 102/build docker image in cirrus

---

components/Op/OpDetailForm.js
components/Op/__tests__/OpDetailForm.spec.js
pages/op/opdetailpage.js
pages/op/opupdatepage.js
server/api/opportunity/__tests__/opportunity.spec.js
server/api/opportunity/opportunity.controller.js
server/api/opportunity/opportunity.js
server/api/opportunity/opportunity.routes.js
server/api/person/__tests__/person.fixture.js
server/api/person/__tests__/person.spec.js

41: opportunity detailpage limitation & add organizer info

Feature opportunities management

---

hocs/publicPage.js

This puts a Provide Feedback button on the side of the page. FIlling in the form raises a ticket in the VP jira project.

add jira issue collector to public page

---

components/Header/HeaderMenu.js
components/LandingPageComponents/Hero.js
components/Op/OpCard.js
components/Org/OrgCard.js
components/Org/OrgList.js
components/__tests__/Header.spec.js

removed antd columns and added vtheme grid system to fix squashed list items

VP-193 quick fix of org list view

---

x/aws/deploy-alpha
x/local-prod

Created another new service so that the EC2s are in the right lb group and VPC. 
Hoping that cirrus will correctly place the stuff it builds.

service name now voluntarily-loadbalanced-service

---

components/Interest/InterestConfirmationCard.js
components/Interest/RegisterInterestSection.js
components/Interest/__tests__/InterestConfirmation.spec.js
package-lock.json

Interest confirmation card shows the thanks message after the user is invited. Also, the phone number is not shown if it is not available.

Test/vp 185/interestconfirmation

---

components/Person/PersonDetailForm.js

Reuse image upload components from OpForm. All test case passed.

Add change avatar for people page

---

.gitignore
components/Person/PersonDetailForm.js
server/api/person/person.controller.js
server/api/person/person.js

The method  is incorrectly added string undefined to person properties.
New user does not have phone and other attribute yet so it should return an empty string
Also the phone is not a required field

VP-207 fixing bug ensureSanitised() add undefined

---

components/Header/HeaderMenu.js
components/__tests__/Header.spec.js
hocs/publicPage.js

Added help menu option linked to service desk. 
Service desk UI needs configuring to look nice.

Vp 223 setup jira service desk

---

components/Footer/Footer.js
components/Footer/FooterMenu.js
components/Header/Header.js
components/Header/HeaderMenu.js
components/Navigation/Navigation.js
components/__tests__/Footer.spec.js
components/__tests__/Header.spec.js
server/util/mockRouter.js

added search bar on title and removed orgs menu.
hidden footer menu except for admins.

Vp 229 search field on title bar

---

server/api/interest/__tests__/interest.spec.js
server/api/interest/interest.controller.js

This should increase  code coverage

Add new unit testing for interest controller api

---

config/config.js
server/services/email/email.js

We now only need to baked the variable into CI then it should be able to read from it.
I will work on the form sanitizing soon.

Hide email api key into env file

---

components/Interest/InterestTable.js
components/Interest/__tests__/interestTable.spec.js
server/api/interest/interest.controller.js

added avatar and click through to user profile

Vp 235 interested volunteers list pretty and useful

---

components/Interest/InterestTable.js

Remove the on row function and add onClick attribute into avatar path
That should solve the issue

Fix bug/VP-252 ticket

---

components/Interest/InterestTable.js
components/LandingPageComponents/Hero.js
components/LandingPageComponents/PersonaSection.js
components/Op/OpDetail.js
components/Op/OpDetailTagsDisplay.js
components/VTheme/VTheme.js

Vp 70 responsive fixes

---

docs/Design-Iteration-Format-Voluntarily
docs/certname.txt
lib/auth/__test__/auth.spec.js
lib/auth/auth.js

Fix case when user is not email verified but we still create a person.  Error occured because me was false causing unexpected return data from interests list. 
better to continue to match the real person but limit what they can do using permissions.

Vp 268 typeerror cannot create property interest on st

---

.cirrus.yml
Dockerfile
config/config.js
x/aws/buildimage

update config so the default APP_URL is the .nz site.

move to voluntarily.nz

---

server/api/opportunity/opportunity.authorize.js
server/api/opportunity/opportunity.constants.js

changed import statements to requires as server side is not ES6 ready. 
fixed tests to match.

Vp 275 syntaxerror unexpected token loading ability co

---

__tests__/home.spec.js
__tests__/landing.spec.js
components/Op/OpCard.js
components/Op/OpDetailForm.js
components/Op/OpListSection.js
components/Op/OpLocationSelector.js
components/Op/__tests__/OpCard.spec.js
components/Op/__tests__/OpDetailForm.spec.js
components/Op/__tests__/OpListSection.spec.js
components/Op/__tests__/OpLocationSelector.spec.js
components/Search/BigSearch.js
components/Search/FilterContainer.js
components/Search/LocationFilter.js
components/Search/__tests__/BigSearch.spec.js
components/Search/filterContainerStyles.less
components/Search/locationFilterStyles.less
components/VTheme/BigSearch.js
lib/redux/reduxApi.js
package-lock.json
pages/op/opupdatepage.js
pages/search/searchpage.js
server/api/location/__tests__/location.spec.js
server/api/location/location.controller.js
server/api/location/locationData.js
server/api/opportunity/__tests__/opportunity.fixture.js
server/api/opportunity/__tests__/opportunity.spec.js
server/api/opportunity/opportunity.controller.js

- Added location to OpCard to make it more clear that the filter is working.
- Filtering is done server-side via the "location" query parameter. Will return all territories **within** a region, or just the matching territory if there are no sub-locations.
- Styling isn't perfect but should be a good start. @waltzaround  maybe you could take a look at improving this at a later date? CSS isn't my strong point

Add location filter to search page

---

__tests__/opdetailpage.spec.js
components/Op/OpListSection.js
components/Op/__tests__/OpListSection.spec.js
components/Search/BigSearch.js
components/Search/FilterContainer.js
pages/search/DatePickerComponent.js
pages/search/searchpage.js

This PR includes little bit of code clean up
Also in the search page. When user choose date or location.The date or location label will be changed to the value user just entered.

UI improvement for search page

---

components/Header/HeaderMenu.js
components/LandingPageComponents/PageTitle.js
components/Person/PersonDetailForm.js

Vp325 profile

---

components/Header/HeaderMenu.js
components/LandingPageComponents/Hero.js
components/Op/OpDetailForm.js
hocs/publicPage.js
lang/en.json

fix height of FullPage so you can actually see the edit button again - bug caused by floating header menu

Vp 388 header menu fix

---

__tests__/opdetailpage.spec.js
components/Op/OpOrganizerInfo.js
components/Op/OpOwnerManageInterests.js
components/Op/OpVolunteerInterestSection.js
pages/op/opdetailpage.js

Refactoring the OpDetailPage to make it easily resuable for ArchivedOpDetailsPage. Not 100% completed but trunk development!

Task/vp 394/refactor op details page to reusable components

---

__tests__/home.spec.js
components/Header/HeaderMenu.js
components/Navigation/Navigation.js
components/Org/OrgDetail.js
components/__tests__/Header.spec.js
package-lock.json
pages/act/actlistpage.js
pages/home/home.js
pages/org/orgdetailpage.js
pages/org/orglistpage.js

Improved org list page and org detail pages

Vp245 improve org list and org detail 

---

components/Op/OpCard.js

Vp396 small op card edits

---

components/Org/OrgCard.js
components/Org/OrgCategory.js
components/Org/OrgDetail.js
components/Org/OrgDetailForm.js
components/Org/OrgList.js
components/Org/__tests__/OrgCard.spec.js
components/Org/__tests__/OrgList.spec.js
pages/org/orgdetailpage.js
server/api/organisation/__tests__/organisation.fixture.js
server/api/organisation/__tests__/organisation.spec.js
server/api/organisation/organisation.js

VP-398 update organisation param type to category

---

server/api/person/__tests__/person.spec.js
server/api/person/person.ability.js
server/api/person/person.routes.js

Small changes for people API. I did not read the api wiki rules carefully so I disallow anonymous user to create a new profile. But with the latest commit this should be good for new user

Small people api rule modification

---

CONTRIBUTORS

Adding myself to contributors.

new contributor

---

CONTRIBUTORS

Vp 82 jasonshi83 firstbranch

---

server/api/opportunity/opportunity.controller.js
server/api/opportunity/opportunity.routes.js
server/api/person/person.controller.js

Derived from ensureSanitized function in person.controller.js.
All fields except description use default sanitization options.
Description field's options set to allow iframes from youtube.
Doesn't actually allow iframes since user-written html in the description field is escaped by the front end before it reaches the server.

Added serverside html sanitization for opportunities form. [VP-342]

---

components/Op/OpOwnerManageInterests.js
docker-compose-alpha.yml
docker-compose-ecs-atlas.yml
pages/op/opdetailpage.js

me id was being compared with requestor object instead of requestor id.

Vp 430 volunteer can see interested parties and the owner

---

docker-compose-alpha.yml
docker-compose-ecs-atlas.yml

no impact on code base - affects script files we should no longer be using.

remove MONGODB defaults

---

__tests__/home.spec.js
components/Member/MemberUl.js
components/Member/RegisterMemberSection.js
components/Member/__tests__/MemberUl.spec.js
components/Member/__tests__/RegisterMemberSection.spec.js
components/Org/OrgDetail.js
components/Person/PersonDetail.js
pages/home/home.js
pages/person/persondetailpage.js
server/api/member/member.controller.js

Personal Profile and View Person now show list of organisations that the person is a member of. 
Personal profile also lists the orgs that a person follows

Vp 423 joinedorgslist component array of joined group i

---

lib/redux/reduxApi.js
pages/op/opdetailpage.js
pages/person/persondetailpage.js
server/api/opportunity/__tests__/opportunity.ability.spec.js
server/api/opportunity/opportunity.ability.js
server/middleware/session/setSession.js

The solution is adding a session in the query so when the set session middleware will add the session back into the request object

Fix bug: draft opportunity not shown when logged in

---

docs/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Create PR template

---

components/Act/ActDetail.js
components/Act/__tests__/ActListSection.spec.js
components/Member/MemberSection.js
components/Member/MemberTable.js
components/Member/MemberUl.js
components/Member/RegisterMemberItem.js
components/Member/RegisterMemberSection.js
components/Member/__tests__/MemberSection.spec.js
components/Member/__tests__/MemberTable.spec.js
components/Member/__tests__/MemberUl.spec.js
components/Member/__tests__/RegisterMemberSection.spec.js
components/Member/__tests__/member.fixture.js
components/Member/__tests__/test.html
components/Op/OpDetail.js
components/Org/OrgDetail.js
components/Org/__tests__/OrgDetail.spec.js
hocs/publicPage.js
pages/about/about.js
pages/home/home.js
pages/org/orgdetailpage.js
pages/test-interest/test-interest.js
pages/test.js
server/api/member/__tests__/member.spec.js
server/api/member/member.constants.js
server/api/member/member.controller.js
server/api/organisation/organisation.js

The Organisation page has a members tab that shows information sections depending on your membership status and for OrgAdmins shows the membership tables allowing them to add and remove members, promote to admins etc.

Vp 426 orgadmin members page list the followers and members

---

components/Search/FilterContainer.js
components/Search/HeaderSearch.js
components/Search/LocationFilter.js
components/Search/__tests__/BigSearch.spec.js
package-lock.json
pages/search/searchpage.js

@waltzaround finally got around to linking the filter up :D.
Functionality is the same as before and I've implemented a reusable FilterContainer component which in theory will reduce the amount of code we write in future to add new filters. Also this component helps us be consistent with how the filter user interactions work (i.e. the date filter is currently a bit different, but once adapted to use FilterContainer the behaviour will be exactly the same as the location filter.
There are some TODOs but I have created tickets for them on Jira and reference them in the comments.

Link location filter with search

---

components/Op/OpListSection.js
config/config.js
lib/redux/reduxApi.js
server/api/health/health.controller.js
server/server.js

I am removing the hard coded alpha appUrl so that we can see if the process.env.APP_URL is being correctly used. 
This may break production for a short time.

test show app_url on startup

---

components/Op/OpListSection.js

Testing alpha - reverting previous change

revert async changes

---

CONTRIBUTORS

<h1> Pull Request : Adding recursiveElk </h1>
<p> VP-82
<h2> Proposed Changes? </h2>
<p>1. Adding Finn to contributors</p>
<h2> Additional Info. </h2>
<h2>Screenshots</h2>

VP-82: Adding recursiveElk to contributors

---

components/Op/OpCard.js
components/Op/OpDetailForm.js
components/Op/__tests__/OpCard.spec.js
components/Org/OrgDetail.js
components/VTheme/IdLine.js
pages/op/opdetailpage.js

1. Make profile page responsive
2. Improve OpCard design
3. fix default location error

Vp467 profile

---

__tests__/home.spec.js
__tests__/landing.spec.js
components/Op/__tests__/OpCard.spec.js
components/Op/__tests__/OpDetail.spec.js
components/Op/__tests__/OpDetailForm.spec.js
hocs/publicPage.js
hocs/securePage.js
server/api/archivedOpportunity/__tests__/archivedOpportunity.controller.spec.js
server/api/image/image.controller.js
server/middleware/session/setSession.js

1.  attempting to load a secure page when not signed in causes an authorize call which loads the auth0 sign in. when signed in returns to the page you were trying to get to.  e.g. goto https://voluntarily.nz/home  when not signed in.
2.  Also remove some console.log lines
3. Also added better output to some exception catches.

VP-408 force authorise for secure pages

---

components/Op/OpCard.js
components/Op/OpDetail.js

`## Proposed Changes? 🤔
1.  corrected links used on the idLink lines to connect to the right pages.

VP-471 correct paths for org and person links

---

x/aws/cloudformation/fargate.yml
x/aws/cloudformation/readme.md

Dev ops change to add AWS cloud formation config to source control
1. 
2. 
3. 
No functional change to actual web application.

Add fargate cloud formation config

---

components/Op/OpCard.js

visual improvements

---

CONTRIBUTORS

Pull Request VP-82
Proposed Change
1. Add Harshani Perera <perera.harshani@gmail.com> as a contributor

Add Harshani Perera as a contributor

---

CONTRIBUTORS

1. Added name to contributors
2. 
3. 

added name to contributors VP-82

---

CONTRIBUTORS

Included Basitha Gamage and ggbmadushan@gmail.com
1. Entered my name and the email to the contributor's list

Updated contributor list

---

CONTRIBUTORS

1. Add George Hardy to contributors list

Added George Hardy as a contributor

---

CONTRIBUTORS
package-lock.json

1. Added my name to the contributors list

added my name

---

CONTRIBUTORS
package-lock.json

1. Added my name to the contributors

Vp 82 santhosh

---

CONTRIBUTORS

1. add Stella name to the contributors list

VP82stella

---

CONTRIBUTORS

1. Adding my name in contributors file.
2. 
3.

[VP-82] Add my name in contributors

---

CONTRIBUTORS
package-lock.json

Added name Kwaku Asamoah and email
1. Added Name Kwaku Asamoah and my Email

Added name (Kwaku)

---

CONTRIBUTORS

adding my name to the list

---

pages/person/persondetailpage.js

(VP-505) Fix server error clicking Edit on /person/:me page 😀
1.  Add withLocations in redux API for person detail page

Fix error in edit person form detail page

---

components/Footer/Footer.js
pages/_document.js

1. Move Google Tag and Atlassian Scripts from head in _document.js to footer.js
2. 
3. 

VP-504 - Move Google Tag and Atlassian Scripts from head to footer

---

components/About/AboutCTA.js
components/Action/ActionCard.js
components/Footer/Footer.js
components/LandingPageComponents/PersonaSection.js
components/Org/OrgDetail.js
components/_intro/index.stories.js

1. Added `rel='noopener noreferrer'` to all external links (`target='_blank'`)
Have not modified the links in email templates - should not be a security concern?

VP-363 External anchor links are missing rel="noopener noreferrer"

---

x/aws/buildimage

1.  the revision tag in the footer includes the UTC Date of the build taken from the REVISION env var. 
2. 
3. 

VP-506 add date to build revision

---

x/aws/buildimage

VP-506 - add date to revision correction

---

components/Person/PersonCard.js
server/api/db/db.controller.js

1. The profile picture display issue has been fixed
2.  A newly added style that can display a person name next line if it is longer. 
3. 

Vp 88 expand ap itest2

---

components/Person/PersonDetail.js
components/Person/PersonDetailForm.js
components/Person/PersonPronoun.js
components/Person/PersonRole.js
components/Person/__tests__/PersonRole.spec.js
components/Tags/TagDisplay.js
pages/home/home.js
pages/person/persondetailpage.js
server/api/person/__tests__/person.fixture.js
server/api/person/__tests__/person.spec.js
server/api/person/person.ability.js
server/api/person/person.constants.js
server/api/person/person.controller.js
server/api/person/person.js

VP-459 replace gender with pronoun in person schema
1.  Add Pronoun with three attributes: subject, object,possessive to Person
2.  Add three textboxes to enter pronouns in person detail form
3.  Display pronoun in  person detail

VP 459 replace gender with pronoun in person schema

---

__tests__/opdetailpage.spec.js
components/Op/OpDetailForm.js
components/Org/OrgDetail.js
lib/redux/reduxApi.js
package-lock.json
package.json
pages/act/actdetailpage.js
pages/op/opdetailpage.js
server/api/opportunity/opportunity.constants.js
server/api/opportunity/opportunity.js

1. Add fromActivity to the op record 
2. Create Opportunity on Act details page button wired to op/new?act=id
3. In Opdetailspage (new) init the op from the act if an activity id is listed.  Copy over the fields. 
4. extended test cover on opdetailspage

VP-297 create opportunity from an activity

---

CONTRIBUTORS

Updated contributors list 
1. 
2. 
3. 

Added Yadwinder to Contributors list

---

CONTRIBUTORS

1. Added myself as a contributor
2. 
3. 

VP-82: added as a contributor

---

CONTRIBUTORS

1. Added name and email as a contributor
2. 
3. 

Add name and email address to CONTRIBUTORS file

---

components/IssueBadge/issueBadge.js
components/Person/PersonBadge.js
server/api/badge/__tests__/badge.spec.js
server/api/badge/badge.controller.js

1. Add loading indicator when issuing new badge in the front end  
2. Add more unit test for the badge API
3. Some minor tweaks in badge API when sending 500 error

Add loading indicator when issuing new badge in the front end

---

CONTRIBUTORS

1. Add name and email to contributor list

VP-82 Add name and email to contributor list

---

components/IssueBadge/issueBadge.js
components/Person/PersonDetail.js

1.  User badge list in personal detail page will be moved to side column
2. Fix issue where issuing badge redirected to undefined URL.

Move user badge list to side column in user detail

---

server/middleware/authorize/__tests__/authorizeRequest.spec.js
server/middleware/authorize/authorizeRequest.js
server/services/authorize/removeUnauthorizedFields.js

1. Fix security issue where opportunities always using action.read
See https://voluntarily.atlassian.net/browse/VP-561 for explanation

VP-561 Fix opportunies always using action.read for security permissions

---

server/api/activity/__tests__/activity.fixture.js
server/api/activity/__tests__/activity.spec.js
server/api/activity/activity.js

1.  added equipment as [String] to the activity schema
2. added examples to the fixture
3. added test that posts a new activity with 3 items in the equipment list and checks they arrive.

VP-565 add equipment list to activity schema.

---

components/Member/MemberExport.js
components/Member/MemberSection.js
components/Member/__tests__/MemberExport.spec.js
components/Member/__tests__/MemberSection.spec.js
lang/en.json
lang/mi.json
server/api/member/member.controller.js

1. Add button for organisation admins, allowing csv export of members (Name,Email,Phone,Role,Date_Added)

Vp-424 Org Admin Member Export Functionality

---

CONTRIBUTORS

🧔 Added myself to the contributors list

---

package-lock.json
package.json

1. Updated Quill as security vulnerabilities were reported.
I've noted that a bunch of the `"optional": true` have been removed automatically.
everything still runs however, maybe this is alright, I'm not sure...
N/a
N/a

`npm audit fix` results

---

components/Member/MemberExport.js
lang/en.json

remove duplicate from language file

correct result of building the lang file.

---

components/Act/ActDetail.js
components/Act/__tests__/ActCard.spec.js
components/Act/__tests__/ActDetail.spec.js
components/Act/__tests__/ActDetailForm.spec.js
components/VTheme/ItemList.js
package.json

1.  add elephant icon to the actdetails page for the space required
2. move status to bottom
3. add better test coverage for when fields are missing.

VP-303 add icon for space required, improve tests

---

CONTRIBUTORS

1. Add myself to contributors
N/A
N/A
N/A

VP-82 Add myself to contributors

---

components/Op/OpListSection.js
components/Op/__tests__/Op.fixture.js
components/Op/__tests__/OpListSection.spec.js

- [+] Run `npm test` and all the tests pass.
- [+] Run `npm run lint` and there are no warnings.
- [+] Not decreased the overall test coverage?
- [+] Included the Jira ID and description in the PR title
1. Added check for the empty field to avoid a server-side error.
2.  If there is an empty duration then it will return '' instead of throwing an error in the server.
3. 

Vp 231 control the presentation order of the listed oppor

---

CONTRIBUTORS

1. Add my name to the CONTRIBUTORS file

VP-82 Add name to contributors list

---

docker-compose-dev.yml
server/services/email/email.js
x/docker-dev/README.md
x/docker-dev/console.sh
x/docker-dev/down.sh
x/docker-dev/logs.sh
x/docker-dev/npm.sh
x/docker-dev/up.sh
x/docker-dev/web-container-start-command.sh

1. Add a new Docker Compose config for a local development environment that includes a MailHog service for capturing email
2. Changes to email transport setup to configure SMTP settings for MailHog service
3. Helper scripts for working with this environment (up, down, logs, etc)
Hopefully this will help anyone working on the app that is behind a firewall that prevents SMTP connections (or developing while offline).

VP-765 Add config and scripts for docker dev env

---

CONTRIBUTORS

1. Add myself to contributors
2. 
3.

vp82 add myself to contributors

---

CONTRIBUTORS

1. Added myself to contributors

Added myself to the contributors list

---

server/api/db/db.controller.js
x/db/migrateTagsToStrings.js

1. allows archivedOpportunity to be used as a collection target in /api/db/fixTag?e=archivedOpportunity
2. 
3. 

VP-805 HOTFIX: add archivedOpportunity to db.controller for tags updates

---

x/db/migrateTagsToStrings.js

1. removed url of alpha database committed in error.
2. 
3. 

VP-810 - restore default mongodb url 

---

server/api/tag/__tests__/tag.controller.spec.js
server/api/tag/tag.controller.js

1. In `tag.controller.js` make the `listTags` function handle the scenario where a tag list record does not exist.
I've had to refactor `listTags` a bit to ensure we can unit test it but as far as I can tell everything is still working as expected.

VP-811 Handle empty taglists collection

---

components/Op/__tests__/OpListSection.spec.js
components/VTheme/__test__/ItemList.spec.js
lib/callApi.js
pages/act/actlistpage.js
pages/api/notify/notify.js
pages/api/notify/org/action.js
pages/api/notify/org/notifyOrg.js
pages/api/registerRequestor/[cmd].js
pages/api/registerRequestor/registerRequestor.js
pages/api/token/[cmd].js
pages/api/token/token.js
pages/search/searchpage.js
pages/test/test-token.js
server/api/activity/activity.controller.js
server/util/initTags.js

1. removed console.log statements that were putting noise into the logs making it hard to see what may be causing a run time error Alpha.

remove unwanted console.logs

---

components/Org/OrgDetailForm.js
components/Org/__tests__/OrgDetailForm.spec.js
server/api/organisation/organisation.js

1. Added Contact Name and Contact Phone Number fields to the create/edit organisation form (when school)
2. 
3. 

VP-591 School contact name and phone number

---

server/api/goal/goal.js

1. protect the goal schema definition from reloads. 
2. 
3. 

protect goal schema

---

components/Person/PersonDetail.js
lib/auth/__test__/auth.spec.js
lib/auth/auth.js
lib/callApi.js
lib/redux/reduxApi.js
server/api/person/__tests__/person.spec.js
server/api/person/person.ability.js
server/api/person/person.constants.js
server/api/person/person.controller.js
server/api/person/person.routes.js
server/middleware/ability/getAbility.js
server/middleware/session/setSession.js
server/services/authorize/__tests__/removeUnauthorizedFields.spec.js
server/services/authorize/removeUnauthorizedFields.js

1. Remove person/by/:param api endpoint
2. Adding back filter user phone number functionality
3. 
None

Vp 572 person information is not filtered based on role

---

__tests__/archivedopdetailpage.spec.js
assets/voluntarily.less
components/Op/OpArchivedHeader.js
components/Op/OpDetailArchived.js
components/Op/__tests__/OpDetailArchived.spec.js
pages/archivedop/archivedopdetailpage.js

1. Split out archived ops into a separate component
2.  Added a header for archived ops signifying that this activity has happened in the past
3.  removed interest section so you cant express interest in an activity that has occurred in the past

Vp844 fix archivedop

---

__tests__/home.spec.js
components/Goal/GoalCard.js
components/Goal/GoalList.js
components/Goal/GoalSection.js
components/Goal/__tests__/GoalCard.spec.js
components/Goal/__tests__/GoalList.spec.js
components/Goal/__tests__/GoalSection.spec.js
lib/callApi.js
lib/redux/reduxApi.js
pages/api/xadmin/assignPersonalGoals.js
pages/goals/goalslistpage.js
pages/goals/index.js
pages/home/home.js
pages/todo.js
server/api/badge/badge.controller.js
server/api/goal/__init__/goal.init.js
server/api/goal/__tests__/goal.fixture.js
server/api/goal/__tests__/goal.spec.js
server/api/goal/goal.controller.js
server/api/goal/goal.js
server/api/personalGoal/__tests__/personalGoal.lib.spec.js
server/api/personalGoal/__tests__/personalGoal.spec.js
server/api/personalGoal/personalGoal.controller.js
server/api/personalGoal/personalGoal.js
server/api/personalGoal/personalGoal.lib.js
server/middleware/session/__tests__/setSession.spec.js

1. new components to display GoalCard, GoalList and GoalSection
2. new admin/utility page to list available goals and assign a goal category to oneself (For testing)
3. API and lib function to assign a goal category to a person id.
4. home page updated to get personalGoals list and display them using GoalSection.
5. added more goals to goal.init.js - autoload these using the /admin page
These components display the currently assigned list of goals for a person on their home page.  
In this version theres no way to remove them once completed and we don't run the evaluation tests yet.

VP-772 goals and personal goals clientside

---

components/Org/OrgDetailForm.js
components/Org/__tests__/OrgDetailForm.spec.js
server/api/organisation/organisation.js

1. Added Address field to the organisation form page
2. 
3. 

VP-593 Added Address field to the organisation form page

---

components/Op/OpDetailForm.js

VP-851 Moved 'Where and when' section on op form to the top

---

components/examples/hooks.js
pages/test/test-hooks.js

1. Add component/examples/hooks.js containing some example components that illustrate use of hooks  - useState and useEffect.
2. Add test/test-hooks page to demonstrate the example.
3. also shows use of nested css styled-components.
Based on demo given to the interns.

VP-862 Hooks example useState, useEffect

---

components/LandingPageComponents/Hero.js
components/LandingPageComponents/PageTitle.js
components/LandingPageComponents/PersonaSection.js
pages/landing/landing.js

1. Make the "who we help" section responsive on the homepage
2. 
3. 

Vp 860/homepage responsiveness part two

---

components/Org/OrgDetailForm.js

1. Moved org category to top of page
2. Changed category label and desc to those written in card
3. Used FormattedMessage for these strings
4. Moved the School section to beneath the Contact section

VP-872 Org page section layout changes

---

pages/act/actdetailpage.js

1.  test for presence of the act prop before trying to use it in the helmet.  When page is first rendered the activity may not be in the redux store and still loading. so we should not depend on it.
2. 
3.

VP-889 fix problem loading activity page after editing.

---

components/Goal/GoalCard.js
pages/api/xadmin/assignPersonalGoals.js
pages/home/home.js
server/api/goal/__init__/goal.init.js
server/api/member/__tests__/member.controller.spec.js
server/api/member/findMy.js
server/api/member/member.lib.js
server/api/organisation/__tests__/organisation.fixture.js
server/api/organisation/__tests__/organisation.lib.spec.js
server/api/organisation/__tests__/organisation.spec.js
server/api/organisation/organisation.lib.js
server/api/personalGoal/personalGoal.controller.js
server/api/personalGoal/personalGoal.lib.js

1. Added functions that allow a person's organisation to be identified and to calculate the degree of completeness for filling in the org profile.  
2. goal.init updated so that the teacher org profile card passes when 75% of the 10 key fields have been filled in.  
3. Test is run when the teacher visits their dashboard.  Currently the completed card is shown with a trophy rather than deleted. 
still to do hide completed cards after a short period
update the completed date field.

VP-852 goal evaluation

---

components/Interest/InterestSection.js
components/Interest/__tests__/InterestSection.spec.js
components/Loading.js
components/Op/OpOwnerManageInterests.js
pages/op/opdetailpage.js

1. Move 'Interested Volunteers' above the 'Danger Zone' section
2. 
3. 

VP-866 Move 'Interested Volunteers' above the 'Danger Zone' section

---

lib/auth/auth.js

1. This corrects a regression where I moved the createPersonFromUser call out of the exception handler.  Putting it back fixes the sign in problem along with setting the correct headers.
2. 
3. 

VP-900 create person when 403 returned

---

components/Org/OrgDetailForm.js

Used FormattedMessage instead of hardcoded string
1. 
2. 
3. 

VP-861 Updated 'About your Organisation' field description text

---

server/api/school-invite/__tests__/school-invite.controller.spec.js
server/api/school-invite/school-invite.controller.js

1. Ensure people signed up via school invite have opportunity provider role
2. Ensure people signed up via school invite get the "First steps for a new school" personal goals on their dashboard

VP-910 School invite OP role and goal cards

---

server/api/opportunity/__tests__/opportunity.util.fixture.js
server/api/opportunity/__tests__/opportunity.util.spec.js
server/api/opportunity/opportunity.util.js

1. Add unit tests for getLocationRecommendations function
2. While writing the tests I noticed issues with getLocationRecommendations that meant it was often returning results in an inconsistent order so I refactored the function slightly to make it give results in a consistent order (while retaining what I believe the original intent was)

VP-924 Add tests for getLocationRecommendations

---

server/api/goal/goal.controller.js

1. This change fixes a unit test that was failing occasionally - I've written up a bit more detail in VP-932: https://voluntarily.atlassian.net/browse/VP-932

VP-932 Add additional default sort field to goals

---

__tests__/home.spec.js
components/Act/ActDetailForm.js
components/Act/__tests__/ActDetailForm.spec.js
components/Org/__tests__/OrgDetailForm.spec.js
components/Person/__tests__/PersonDetailForm.spec.js
server/util/mock-dom-helpers.js

1. Where needed use the `MockWindowScrollTo` class during unit tests

VP-938 Mock window.scrollTo during unit tests

---

components/Search/FilterContainer.js
pages/search/searchpage.js

1. Fixes a couple of console warnings related to props that don't match their prop type definitions

VP-944 Fix search page prop warnings

---

server/api/goal/__tests__/loadGoals.spec.js
server/api/goal/loadGoals.js

1. The loadGoals test isn't `await`ing the promise returned by the `loadGoals` function so sometimes the test will fail because not all goal records are loading in time.

VP-945 Fix loadGoals test occasionally failing

---

components/Op/OpList.js

1. Change rows and cols back to grid
2. 
3. 

VP-935/change_oplist_to_grid: changed row and cols back to grid

---

.cirrus.yml
.gitignore
next.config.js
package.json

1. Update next.config.js to set a unique `distDir` for each test (when `NODE_ENV=test`)

VP-950 Parallel tests

---

CONTRIBUTORS
docs/Docker.md

1. Include the `-f` parameter for the `docker-compose` command to locate its input file
At least when trying locally I got:
```bash
$ ~/Development/javascript/workspace/vly2$ docker-compose docker-compose.yml up -d --build
No such command: docker_compose.yml
```

Add f parameter docker compose

---

server/api/goal/__init__/goal.init.js
server/api/personalGoal/GoalTests.js
server/api/personalGoal/personalGoal.lib.js

Updated SchoolSafe card so that it evaluates to true if the person has been assigned the SchoolSafe-test badge.  Start link is to /goal/school/safe but this page is still a todo.

VP-780 schoolSafe goal card linked to badgeclass

---

components/examples/edits.js
pages/test/test-edits.js

Adds a set of demonstration components that show how to toggle between a display and edit view in place, how to stack display items and add a new item. 
using useState and simple callbacks.
This is an example of how to build a component out of more simple components separating the display and edit elements from the logic, storage and listing elements.

VP-1049 example editable components in a list

---

server/api/goal/__init__/goal.init.js
server/api/goal/loadGoals.js
x/db/load-goals.js
x/docker-dev/reset-database.sh

1. Add a script to reset the local docker dev environment database
Run via `x/docker-dev/reset-database.sh`
This script resets the state of the database to an initial state to ease
testing. It drops the database, imports school metadata, and loads
goals.

VP-1065 Add database reset script

---

components/Person/PersonDetailForm.js

1. Hide role selector in prod for users so they cant make themselves admins

Vp1063 hide role selector prod

---

components/Header/Header.js
lib/sec/keys.js
pages/api/token/token.js

In production mode the public and private keys for token generation were being read from environment variables. However only the private key was being set in the container. This meant that jwt verify fails because it used a different pub key to verify (a warning string).  This resulted in the invalid algorithm message.
This change puts the public key prod.pub.pem in the lib/sec folder and reads it into the keys. 
also changed the response from 500 to 404. In this error when we had the wrong keys 500 is the appropriate response however usually the JWT failure would arise from an invalid token and thus we refuse the request - we can't find the resource the jwt is requesting. 
Note - public keys are not secret - they are made available so that the JWT can be verified. Only the private key …

VP-1077 - ensure production public key is in the release.

---

package-lock.json
package.json
server/middleware/session/__tests__/jwtVerify.spec.js
server/middleware/session/jwtVerify.js
server/middleware/session/setSession.js

Added full JWT Verify call against the Auth0 signed idToken to ensure people are signed in properly and not faking the token.
When a page or API call is requested from the server the request is passed through setSession which checks whether the person is signed in or not.  
setSession checks for either a Cookie called idToken or a header Authorization: Bearer {idToken} 
usually The cookie is present on page requests, the header on API requests. 
idToken is a JSON Web Token (JWT) that was stored when the person completed sign in via Auth0. It is a JSON object signed by Auth0 private key and BASE64 encoded. 
Previously we simply decoded the payload meaning that the token could be spoofed by changing email address and generating a new idToken.  
Now we verify the signature against the Auth0 …

VP-1030 server setSession validate JWT for sign in

---

server/api/archivedOpportunity/__tests__/archivedOpportunity.ability.spec.js
server/api/archivedOpportunity/__tests__/archivedOpportunity.fixture.js
server/api/archivedOpportunity/archivedOpportunity.ability.js
server/api/archivedOpportunity/archivedOpportunity.constants.js
server/api/archivedOpportunity/archivedOpportunity.controller.js
server/api/archivedOpportunity/archivedOpportunity.routes.js
server/services/authorize/removeUnauthorizedFields.js

1. Implement permissions on Archived Opportunities API

VP-1084 Archived opportunity API permissions

---

components/Member/InviteMembers.js

- [ x] Run `npm test` and all the tests pass.
- [ x] Run `npm run lint` and there are no warnings.
- [] Not decreased the overall test coverage?
- [ x] Included the Jira ID and description in the PR title
1. quick emergency fix for org members tab styling

Vp1232 fix tab styling

---

server/api/badge/__tests__/badge.permissions.spec.js
server/api/badge/__tests__/badge.spec.js
server/api/badge/badge.controller.js

1. Add permissions & tests for badge API end point

VP-1085 Badge API permissions

---

server/api/activity/__tests__/activity.spec.js
server/api/activity/activity.controller.js
server/api/opportunity/__tests__/opportunity.spec.js
server/api/opportunity/opportunity.controller.js
server/api/person/__tests__/person.spec.js
server/api/person/person.controller.js
server/api/person/person.routes.js

1. The & symbol doesn't get sanitized in the opportunity and person form
2. Added a unit test for activity form that checks if special characters work in the title/name field

VP-803 The '&' symbol can be used correctly in the opportunity and person form

---

server/api/image/__tests__/image.spec.js
server/api/image/image.controller.js

1. Add permissions to image API (only allow upload for authenticated users)

VP-1088 Add image API permissions

---

CONTRIBUTORS

1. Add my name to contributors file
2. 
3. 

Update CONTRIBUTORS with my name, Jill Glass

---

components/Person/PersonDetailForm.js
lang/en.json

- [/] Run `npm test` and all the tests pass.
- [/] Run `npm run lint` and there are no warnings.
- [/] Not decreased the overall test coverage?
- [/] Included the Jira ID and description in the PR title
1. change language on persondetailform from avatar to Profile Photo

VP-1155 copy change for Profile Photo

---

server/api/member/__tests__/member.ability.fixture.js
server/api/member/__tests__/member.ability.spec.js
server/api/member/__tests__/member.spec.js
server/api/member/member.ability.js
server/api/member/member.controller.js
server/api/member/member.js
server/api/member/member.routes.js
server/util/test-generate-session.js

1. Add permissions to Member API

VP-1092 Member API permissions

---

server/api/organisation/organisation.constants.js

1. Define `SchemaName` in `organisation.constants.js`

VP-1307 Add SchemaName variable for Organisation

---

CODE_OF_CONDUCT.md

From sandeep@hashnode to team@vly
- [ N/A] Run `npm test` and all the tests pass.
- [N/A ] Run `npm run lint` and there are no warnings.
- [ N/A] Not decreased the overall test coverage?
- [ N/A] Included the Jira ID and description in the PR title
1. change contact email in code of conduct to a voluntarily team email

vp1310 Fixed contact email

---

components/Story/ExpandText.js

1. Read more does not appear if the text is not long enough to be expanded

VP 1230 Read more does not appear if the text is not long

---

server/api/story/__tests__/story.ability.fixture.js
server/api/story/__tests__/story.ability.spec.js
server/api/story/__tests__/story.spec.js
server/api/story/story.ability.js
server/api/story/story.controller.js
server/api/story/story.js
server/api/story/story.routes.js

1. Implement basic story API permissions

VP-1096 Story API permissions

---

server/api/interest/__tests__/interest.ability.fixture.js
server/api/interest/__tests__/interest.ability.spec.js

1. Add a test to attempt to reproduce bug

VP-1326 Add volunteer+op test for interest API

---

__tests__/act/actlistpage.spec.js
components/Act/ActList.js
lang/en.json
pages/act/actlistpage.js

1. remove dummy category component on resources page

VP-849 - removed example faceted search from Activity page.

---

__tests__/op/opdetailpage.spec.js
pages/op/opdetailpage.js

1. Fix error with new opportunity form and `sync` flag

VP-1363 Fix new opportunity form

---

.babelrc
components/Person/PersonDetailForm.js

1. add `compact: true` to babel config to fix styling deoptimisation
2. fix duplicate FormattedMessage causing errors for npm build:lang

VP1366 - Proposed fix for Babel styling deoptimisation + FormattedMessage fix

---

server/api/person/person.constants.js
server/api/person/person.controller.js

1. placeOfWork field was not being return from GET people/:id
2. 
3. 

VP-1369 Include placeOfWork as a 'personal field'

---

CONTRIBUTORS

1. Added myself to the contributors file
Running `npm run lint` produced one warning. However, the change to CONTRIBUTORS should not affect this, so I asume it is an existing warning?
```
➜  vly2 git:(VP-82-jordansimsmith) ✗ npm run lint
> @voluntarily/vly2@1.0.0 lint /home/jordan/Repositories/vly2
> standard
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
```

VP-82: added name to list of contributors

---

pages/terms/term-en-md.js

- [* ] Run `npm test` and all the tests pass.
- [ *] Run `npm run lint` and there are no warnings.
- [ *] Not decreased the overall test coverage?
- [* ] Included the Jira ID and description in the PR title
1. Added updated version of the terms and conditions

 Added updated version of Terms and Conditions

---

server/api/interest/interest.controller.js

Messages window does not show the name of the author of each message.  
Fix the listInterests controller to populate out the author details.

populate messages to include author

---

CONTRIBUTORS

1. Added my name to the contributors list

[VP-82] Added my name to the contributors list

---

components/Interest/RegisterInterestItem.js
components/Op/OpVolunteerInterestSection.js
lang/en.json

1. change copy for anonymous OpVolunteerInterestSection to "Get Involved"
2. small style changes for consistency

VP-1420 improve get interest copywriting

---

components/Op/OpCard.js
components/Op/__tests__/OpCard.spec.js
components/VTheme/VTheme.js

1. add small margin to subtitle to separate it away from time and location

VP-1423. add small margin to opcard

---

components/Interest/RegisterInterestItem.js
components/Org/OrgDetailForm.js
components/VTheme/VTheme.js

1. fix visual bugs in RegisterInterestItem
2. fix visual bugs in OrgDetailForm

Vp 1426 fix visual bugs

---

components/Home/HomeTabs.js
components/Op/OpCard.js
components/Op/OpList.js
components/Op/__tests__/OpCard.spec.js
components/VTheme/VTabs.js
components/VTheme/VTheme.js

VP-1395 Improve State tags on OpCard

---

components/Interest/InterestTable.js
components/Person/PersonCard.js

1. fix image bugs on personcard when images with wierd aspect ratios are added
2. fix mobile view

VP-1371 Fix visual bugs on PersonCard  💄🐛

---

components/Header/HeaderMenu.js

Vp 1485 Change Help to Lost?

---

components/Footer/Footer.js

Corrected the voluntarilyAotearoa social links to be all voluntarilyhq now.
1. 
2. 
3. 

Changed social links

---

components/LandingPageComponents/OfferSection.js

VP-1486 - add pre-register links

---

docs/gettingstarted.md

Very very minor updates to the getting started doc, to make it easier for the next person.

Minor updates to getting started guide (on Mac)

---

CONTRIBUTORS

VP-82: Add name to list of contributors

---

CONTRIBUTORS

- [ ✓ ] Run `npm test` and all the tests pass.
- [ ✓ ] Run `npm run lint` and there are no warnings.
- [ ✓ ] Not decreased the overall test coverage?
- [ ✓ ] Included the Jira ID and description in the PR title
1. Adds my name to CONTRIBUTORS, in line with the instructions left in CONTRIBUTING.md
None

VP-82 - Make a simple change

---

components/Form/Input/TypeOpSelector.js
components/Form/__tests__/TypeOpSelector.spec.js
components/Op/OpDetailForm.js
components/Op/OpListSection.js
components/Search/TypeFilter.js
components/Search/__tests__/TypeFilter.spec.js
lang/en.json
pages/search/searchpage.js

1. Add Op type filter in search bar
2. 
3. 

Vp 1498: client - add component to search bar to toggle between ask or offers. and filter request appropriately

---

CONTRIBUTORS

added name in contributors list

---

components/LandingPageComponents/Hero.js
components/LandingPageComponents/SignUp.js
package-lock.json
pages/landing/landing.js

1. Log In & Sign Up buttons in the landing hero
2. The Sign Up button first presents the actor with a modal. The modal has sign up instructions.
3. 

VP-1457 - Added Log In & Sign Up buttons to the Landing view

---

__tests__/landing.spec.js
components/LandingPageComponents/Hero.js
components/LandingPageComponents/OfferSection.js
lang/en.json
pages/landing/landing.js

VP-1566 - fix landing responsive issues

---

components/LandingPageComponents/OfferSection.js

VP-1573 fix heights and buttons

---

CONTRIBUTORS

VP-82 rashmi

---

components/LandingPageComponents/Hero.js

1. Fix responsive issues on macbook air
2. add sign up back in

VP-1573 landing page improvements

---

__tests__/landing.spec.js
pages/landing/landing.js

1. Remove OpListSection from landing to avoid confusion with new designs going forward

VP1566 - remove oplistpage on landing

---

__tests__/home.spec.js
components/Home/HomeTabs.js
components/Home/__tests__/HomeTabs.spec.js
components/LandingPageComponents/Hero.js
components/LandingPageComponents/OfferSection.js
components/VTheme/VTheme.js
lang/en.json
pages/landing/landing.js

1. remove discover tab for now

Vp1596 remove discover tab for launch

---

CONTRIBUTORS

VP-82: Add Josh McArthur <joshua.mcarthur@gmail.com> to CONTRIBUTORS

---

package-lock.json
public/security.txt

1. Updated package versions to address over 500 vulnerabilities
2. added security.txt for site vulnerability reporting
Using Andrew's email as its the one being used on rest of the places and advised on the security.md doc

VP-1560 add security.txt to site

---

components/Act/ActCard.js
components/Member/MemberSection.js
components/Member/MemberTable.js
components/Member/RegisterMemberSection.js
components/VTheme/AvatarProfileLink.js
pages/act/actdetailpage.js
pages/op/opdetailpage.js
server/api/personalGoal/personalGoal.lib.js

if person is a volunteer and not a member of any org (no member records) the test for org admin would fail trying to loop over the members.  - fix this
also if a person has been deleted but member records still exist they will have null for the person. this causes issues in multiple locations. 
added some protective tests.

VP-1603 some resilience to missing people

---

components/LandingPageComponents/Hero.js

1. Saw mobile in-app browser view on iPhone and was disgusted - fixed image resizing to avoid cropped head.
2. Ended up fixing up portrait ipad view as well

fixed broken images thanks to covid banner

---

components/LandingPageComponents/Hero2.js

VP-1597 update text button from teacher to business sign up

---

components/Footer/Footer.js
components/__tests__/Footer.spec.js
lang/en.json

Vp1596 fix footer

---

.github/workflows/push-master.yml

Preinstall pre-reqs on server and remove from build step

---

CONTRIBUTORS

VP-82 Adding my name to the contributor's list.

---

.github/workflows/push-master.yml

Ok maybe that makes sense

---

components/Act/ActListSection.js

change the List configuration on ActDetailSection so that is responsive to the page width. 
When the page is under 1200 wide the sidebar is hidden. Above that line the grid is 3 cols, below it reduces 3,2,1 down iPhone level.

make grid more responsive.

---

components/Footer/Footer.js
components/Goal/GoalSection.js
components/Header/Header.js
components/Op/ActiveOpsSection.js
components/Op/InterestedOpsSection.js
pages/terms/privacy.js
pages/terms/terms.js

1. fixed header behaviour on alpha - it was covering the COVID banner before this PR
2. shifted footer version up so it visible on alpha
3. small quality of life tweak on privacy and terms

VP-1596 UX cleanup on header and footer

---

components/Footer/Footer.js
components/Footer/WomensRefuge.js

REplaced the womens refuge button in the footer.
This needed major rework - we now don't rely on the source scripts which failed during server side rendering.  Instead we just show our own iframe with the remote content provided. Using react open and close to control visibility.
This is not Modal . it just expands into the footer. which means that you can scroll away from it if necessary.
The large close button is not quite aligned.

VP-574 add womens refuge button

---

components/Footer/WomensRefuge.js
components/Footer/__tests__/WomensRefuge.spec.js
pages/reports/summary.js

1. Add a single. missing.character. that was stopping the activity count from being displayed :man_facepalming: 

VP-1608: Bugfix for activity count not being displayed

---

components/Footer/Footer.js
components/Footer/WomensRefuge.js
components/VTheme/VTheme.js

1. fix visual glitches by removing the shielded site

Vp1596 fix header

---

components/Footer/Footer.js
components/__tests__/Footer.spec.js

1. Added "Code of Conduct" link to footer.

Added "Code of Conduct" link to footer

---

components/LandingPageComponents/OfferSection.js

1. rename and change route of offer to help / ask for help

Vp1688 offer to help section is ready

---

components/Op/OpBanner.js

1. Removed "Venue" from OpBanner.js (Ticket: VP-1522)

Removed "venue" from OpBanner.js

---

pages/terms/privacypage.js

1. copy changes to privacy policy

push fixes to copy

---

components/Footer/Footer.js
pages/_document.js

1. remove GA, and replace it with GTM
Anyone mind sanity checking this and making sure its actually passing data?
Trying to avoid screwing up analytics

VP-1689   Replace Google Analytics with Google Tag Manager

---

package-lock.json
package.json

Update to lattest version of next js to fix security alert
2. 
3. 

VP-1701 upgrade nextjs

---

components/Person/PersonDetailForm.js

1. Added tooltip to PersonDetailForm for "Skills and Interests", ticket VP-1651.

Added tooltip to PersonDetailForm for "Skills and Interests".

---

components/VTheme/VTheme.js

1. change card image behavior to centre when they overflow
ie: wierdly shaped images that are uploaded get centered

VP1705 fix image behavior

---

components/testredux/LocalUseStateTest.js
pages/test/test-state.js

Adds to the state examples a useState version

vp-1706 Tutorial - add useState example

---

components/Act/ActBanner.js
components/Act/ActCardSuggest.js
components/Act/ActOpsPanel.js
components/Act/ActReadMore.js
components/Act/__tests__/ActBanner.spec.js
components/Act/__tests__/ActCardSuggest.spec.js
components/Act/__tests__/ActReadMore.spec.js
components/Act/__tests__/ActTryBelow.spec.js
components/Act/__tests__/ActUnknown.spec.js
components/Footer/Footer.js
components/Op/OpType.js
components/VTheme/ItemList.js
config/clientConfig.js

A document link panel is added to the Activity page banner to link to the knowlege base. 
The equipment list in resources is hidden if the list is zero length.

VP - 1657 Link to Knowledge base

---

.cirrus.yml

- HOT FIX
Restore Cirrus.yml so that we can do a deployment

restore cirrus ci so we can get a deploy

---

README.md

HOT FIX - minor change to trigger a deployment

VP-1680 single word change

---

pages/xrobots.txt/index.js
public/robots.txt
server/server.js

1. have production robots.txt allow for search crawlers
Please review the allowed paths.

VP-1533 robots.txt for prod updated for SEO

---

components/Interest/RegisterInterestMessageForm.js

Allow messages to be 400 instead of 400 characters.

VP-1730 allow 400 character messages

---

CONTRIBUTORS

Adding myself to the contributors list

---

components/quiz/__tests__/quiz.fixture.js
pages/goal/volunteer/ready.js

- [*] Run `npm test` and all the tests pass.
- [*] Run `npm run lint` and there are no warnings.
- [*] Not decreased the overall test coverage?
- [*] Included the Jira ID and description in the PR title
1. Changed the video from the broken one
2. Added new questions
3. Updated the test

Vp 1634 update onboarding school ready video text

---

config/env.js
config/importEncryptedEnv.js
next.config.js

1. This resolves the issue where nextjs isn't passing environment variables down to the frontend code.
This is a bugfix to the previous pr for VP 1732.

Pass environment variables through to frontend

---

__tests__/goal/school/ready.spec.js
components/quiz/__tests__/quiz.spec.js
pages/goal/volunteer/ready.js

- [ *] Run `npm test` and all the tests pass.
- [* ] Run `npm run lint` and there are no warnings.
- [ *] Not decreased the overall test coverage?
- [ *] Included the Jira ID and description in the PR title
1. Fixed error test

VP1634-Fixed failed tests

---

CONTRIBUTORS

VP-82 - Added my name to the contributors file

---

.cirrus.yml

update the cirrus.yml with the name and key of the encrypted env file.
1. 
2. 
3. 

VP-1751 - add env secret to cirrus ci

---

.github/workflows/push.yml

Add alpha build step

---

pages/api/health/config.js
server/server.js

print the environment on startup - debugging the encrypted vars.

VP-1751 print env on startup

---

.github/workflows/push.yml

Added commit id as REVISION env var to be used by footer.
Two Options: 
1. Set during build time
2. Set as env var at docker run
Personally I prefer option 2.

added commit id for build args

---

.github/workflows/push.yml
Dockerfile
config/serverConfig.js

1. add revision as arg to build task
2. remove env var during docker run as its already setup at build

add revision env var to configs

---

.github/workflows/push.yml

1. update beta deployment task

update beta deployment task

---

CONTRIBUTORS

adding my name to contributors file

---

.github/workflows/push.yml

1. update correct name for beta cluster for deploy

fix beta cluster name

---

.github/workflows/push.yml

add github actions that cause a push to live  or beta branches to trigger a deployment

VP-1762 add beta, gamma and live deploy

---

lang/en.json

run npm run build:lang to correct language file

VP-1762 fix lang file

---

.github/workflows/deploy-beta.yml

beta service is called voluntarily-beta-service

VP-1762 fix service name

---

.github/workflows/deploy-gamma.yml
.github/workflows/deploy-live.yml

beta working - create equivalent live and gamma deployment actions

Vp 1762 create live deploy

---

.github/workflows/deploy-live.yml

Release 20 April 2020, 13:25

---

.github/workflows/deploy-gamma.yml

fix the service name on gamma.

VP-1762 fix service name on gamma

---

.github/workflows/deploy-alpha.yml
.github/workflows/deploy-beta.yml
.github/workflows/deploy-live.yml
.github/workflows/testall.yml

splits the push.yml file into two a testall.yml that runs on each push to a branch but excludes pushes to master and releases/*
and deploy_alpha, beta, etc. that runs on push to master. or releases branch

VP-1777 factor out deployments from tests

---

server/api/location/locationData.js

1. this reverts the location picker to remove the suburbs list.  the suburbs are a problem as they are not embedded in the heirarchy so we can't see which region each suburb is in. Also lots of other towns and localities missing.
2. 
3. 

VP-1768 remove suburbs

---

pages/home/home.js
server/api/opportunity/opportunity.util.js

fix 500 error on home page arising from merge conflict.  
remove extra console.log

VP-1772 fix merge bug

---

.github/workflows/testall.yml
components/Act/ActAboutPanel.js
components/Act/ActOpsPanel.js
components/Act/ActTabs.js
pages/act/actdetailpage.js

1. If I am a volunteer and NOT a basic asker too then hide the offers tab and offers section on the activity detail page so that I don't see what other volunteers are offering.
2. 
3. 

VP 1784 as a volunteer only I don't see other offers on an activity

---

assets/notices/conduct-short-en.md

VP-1754: Remove extraneous 'i'

---

components/Act/ActOpsPanel.js

1. fix a single import preventing deploy from happening

VP1829 - missing .js filename extension

---

components/Act/ActOpsPanel.js

VP1829 - fix import oversight in ActiveOpsSection

---

components/Op/OpCard.js
components/Op/OpTabs.js
pages/landing/landing.js

- [x ] Included the Jira ID and description in the PR title
1.  Chat should now work on Alpha

VP1829 - remove prod toggle so chat appears on Alpha

---

components/LandingPageComponents/GiveContentSection.js
components/LandingPageComponents/GiveSupportSection.js
components/LandingPageComponents/HelpOrgsSection.js
components/LandingPageComponents/HelpSocialSection.js
components/LandingPageComponents/Hero.js
components/LandingPageComponents/TakeSupportSection.js
components/VTheme/VTheme.js

Vp1848   new landing page

---

components/LandingPageComponents/GiveContentSection.js
components/LandingPageComponents/GiveSupportSection.js
components/LandingPageComponents/HelpOrgsSection.js
components/LandingPageComponents/Hero.js
components/LandingPageComponents/HowSection.js
components/LandingPageComponents/OfferSection.js
components/VTheme/VTheme.js
pages/landing/landing.js

1. Responsive fixes to prior PR

Vp1848   landing page

---

__tests__/feedback/feedbacksubmitpage.spec.js
lang/en.json
pages/feedback/feedbacksubmitpage.js

1. Increase friendliness of feedback page
2. Add button to recommended ops
3. Increase error reporting

VP-1862: Feedback page improvements

---

components/LandingPageComponents/Hero.js

1. fix link on landing page
2. 
3. 

fix link on landing page

---

components/Op/OpAboutPanel.js
components/Op/OpShortForm.js

1. restore description field to shortforms so that demos can actually occur

VP1871 - Adam Emergency Fix for demo

---

.github/workflows/deploy.yml

- [Y] Run `npm test` and all the tests pass.
- [Y] Run `npm run lint` and there are no warnings.
- [Y] Not decreased the overall test coverage?
- [Y] Included the Jira ID and description in the PR title
1. updated deploy script to not use deprecated environment variable setting
see https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

VP-1885 updated deploy script to not use deprecated environment variable setting
